/**
 * Shunya Labs supported languages (200+).
 * Codes from https://docs.shunyalabs.ai/languages
 */

export interface ShunyaLanguage {
  code: string;
  label: string;
  native?: string;
}

/** Indic (32) + European (58) + Asian (28) + African (41) + Middle East (23) + Americas etc. */
export const SHUNYA_LANGUAGES: ShunyaLanguage[] = [
  // Indic
  { code: 'en', label: 'English', native: 'English' },
  { code: 'hi', label: 'Hindi', native: 'हिन्दी' },
  { code: 'bn-IN', label: 'Bengali (India)', native: 'বাংলা' },
  { code: 'bn-BD', label: 'Bengali (Bangladesh)', native: 'বাংলা' },
  { code: 'ta', label: 'Tamil', native: 'தமிழ்' },
  { code: 'te', label: 'Telugu', native: 'తెలుగు' },
  { code: 'kn', label: 'Kannada', native: 'ಕನ್ನಡ' },
  { code: 'ml', label: 'Malayalam', native: 'മലയാളം' },
  { code: 'mr', label: 'Marathi', native: 'मराठी' },
  { code: 'gu', label: 'Gujarati', native: 'ગુજરાતી' },
  { code: 'pa', label: 'Punjabi', native: 'ਪੰਜਾਬੀ' },
  { code: 'od', label: 'Odia', native: 'ଓଡ଼ିଆ' },
  { code: 'ur', label: 'Urdu', native: 'اردو' },
  { code: 'ne', label: 'Nepali', native: 'नेपाली' },
  { code: 'awa', label: 'Awadhi', native: 'अवधी' },
  { code: 'bgh', label: 'Bagheli', native: 'बघेली' },
  { code: 'bho', label: 'Bhojpuri', native: 'भोजपुरी' },
  { code: 'brx', label: 'Bodo', native: 'बड़ो' },
  { code: 'hne', label: 'Chhattisgarhi', native: 'छत्तीसगढ़ी' },
  { code: 'doi', label: 'Dogri', native: 'डोगरी' },
  { code: 'grt', label: 'Garo', native: 'गारो' },
  { code: 'gon', label: 'Gondi', native: 'गोदी' },
  { code: 'bgc', label: 'Haryanvi', native: 'हरियाणवी' },
  { code: 'hoc', label: 'Ho', native: 'हो' },
  { code: 'ks', label: 'Kashmiri', native: 'कश्मीरी' },
  { code: 'kha', label: 'Khasi', native: 'खासी' },
  { code: 'kov', label: 'Khond', native: 'खोंड' },
  { code: 'kok', label: 'Konkani', native: 'कोंकणी' },
  { code: 'mag', label: 'Magahi', native: 'मगही' },
  { code: 'mai', label: 'Maithili', native: 'मैथिली' },
  { code: 'mup', label: 'Malvi', native: 'मालवी' },
  { code: 'mwr', label: 'Marwari', native: 'मारवाड़ी' },
  { code: 'lus', label: 'Mizo', native: 'मिजो' },
  { code: 'unr', label: 'Mundari', native: 'मुंडारी' },
  { code: 'raj', label: 'Rajasthani', native: 'राजस्थानी' },
  { code: 'sat', label: 'Santali', native: 'संताली' },
  { code: 'sd', label: 'Sindhi', native: 'سندھی' },
  { code: 'tcy', label: 'Tulu', native: 'ತುಳು' },
  // European
  { code: 'en-GB', label: 'English (UK)', native: 'English UK' },
  { code: 'en-US', label: 'English (US)', native: 'English US' },
  { code: 'en-AU', label: 'English (Australia)', native: 'English Australia' },
  { code: 'en-CA', label: 'English (Canada)', native: 'English Canada' },
  { code: 'en-ZA', label: 'English (South Africa)', native: 'English South Africa' },
  { code: 'en-IE', label: 'English (Ireland)', native: 'English Ireland' },
  { code: 'fr', label: 'French', native: 'Français' },
  { code: 'fr-FR', label: 'French (France)', native: 'Français (France)' },
  { code: 'fr-CA', label: 'French (Canada)', native: 'Français (Canada)' },
  { code: 'fr-CH', label: 'French (Switzerland)', native: 'Français (Suisse)' },
  { code: 'de', label: 'German', native: 'Deutsch' },
  { code: 'es', label: 'Spanish', native: 'Español' },
  { code: 'es-ES', label: 'Spanish (Spain)', native: 'Español (España)' },
  { code: 'it', label: 'Italian', native: 'Italiano' },
  { code: 'pt', label: 'Portuguese', native: 'Português' },
  { code: 'pt-BR', label: 'Portuguese (Brazil)', native: 'Português (Brasil)' },
  { code: 'pt-AF', label: 'Portuguese (Africa)', native: 'Português (African)' },
  { code: 'nl', label: 'Dutch', native: 'Nederlands' },
  { code: 'ru', label: 'Russian', native: 'Русский' },
  { code: 'pl', label: 'Polish', native: 'Polski' },
  { code: 'el', label: 'Greek', native: 'Ελληνικά' },
  { code: 'uk', label: 'Ukrainian', native: 'Українська' },
  { code: 'ro', label: 'Romanian', native: 'Română' },
  { code: 'cs', label: 'Czech', native: 'Čeština' },
  { code: 'hu', label: 'Hungarian', native: 'Magyar' },
  { code: 'sv', label: 'Swedish', native: 'Svenska' },
  { code: 'da', label: 'Danish', native: 'Dansk' },
  { code: 'fi', label: 'Finnish', native: 'Suomi' },
  { code: 'sk', label: 'Slovak', native: 'Slovenčina' },
  { code: 'sl', label: 'Slovenian', native: 'Slovenščina' },
  { code: 'bg', label: 'Bulgarian', native: 'Български' },
  { code: 'hr', label: 'Croatian', native: 'Hrvatski' },
  { code: 'sr', label: 'Serbian', native: 'Srpski' },
  { code: 'be', label: 'Belarusian', native: 'Беларуская' },
  { code: 'ca', label: 'Catalan', native: 'Català' },
  { code: 'eu', label: 'Basque', native: 'Euskera' },
  { code: 'sq', label: 'Albanian', native: 'Albanian' },
  { code: 'cy', label: 'Welsh', native: 'Cymraeg' },
  { code: 'bar', label: 'Bavarian', native: 'Boarisch' },
  // Asian
  { code: 'zh-CN', label: 'Chinese (Mandarin)', native: '中文' },
  { code: 'zh-HK', label: 'Chinese (Cantonese)', native: '廣東話' },
  { code: 'ja', label: 'Japanese', native: '日本語' },
  { code: 'ko', label: 'Korean', native: '한국어' },
  { code: 'th', label: 'Thai', native: 'ไทย' },
  { code: 'vi', label: 'Vietnamese', native: 'Tiếng Việt' },
  { code: 'id', label: 'Indonesian', native: 'Bahasa Indonesia' },
  { code: 'ms', label: 'Malay', native: 'Bahasa Melayu' },
  { code: 'tl', label: 'Tagalog', native: 'Tagalog' },
  { code: 'my', label: 'Burmese', native: 'မြန်မာ' },
  { code: 'km', label: 'Khmer', native: 'ខ្មែរ' },
  { code: 'lo', label: 'Lao', native: 'ລາວ' },
  { code: 'bo', label: 'Tibetan', native: 'བོད་' },
  { code: 'jv', label: 'Javanese', native: 'Javanese' },
  { code: 'ceb', label: 'Cebuano', native: 'Cebuano' },
  { code: 'ace', label: 'Acehnese', native: 'Acehnese' },
  { code: 'bug', label: 'Bugis', native: 'Bugis' },
  // Middle Eastern
  { code: 'ar', label: 'Arabic', native: 'العربية' },
  { code: 'ar-EG', label: 'Arabic (Egyptian)', native: 'العربية المصرية' },
  { code: 'ar-AE', label: 'Arabic (Gulf)', native: 'العربية الخليجية' },
  { code: 'ar-LB', label: 'Arabic (Levantine)', native: 'العربية الشامية' },
  { code: 'ar-IQ', label: 'Arabic (Iraqi)', native: 'العربية العراقية' },
  { code: 'ar-MA', label: 'Arabic (Maghrebi)', native: 'Arabic (Maghrebi)' },
  { code: 'ar-TD', label: 'Arabic (Chadian)', native: 'Arabic (Chadian)' },
  { code: 'he', label: 'Hebrew', native: 'עברית' },
  { code: 'fa', label: 'Persian', native: 'فارسی' },
  { code: 'tr', label: 'Turkish', native: 'Türkçe' },
  { code: 'ku', label: 'Kurdish (Kurmanji)', native: 'Kurdî' },
  { code: 'ckb', label: 'Kurdish (Sorani)', native: 'کوردی' },
  { code: 'ps', label: 'Pashto', native: 'پښتو' },
  // African
  { code: 'sw', label: 'Swahili', native: 'Kiswahili' },
  { code: 'af', label: 'Afrikaans', native: 'Afrikaans' },
  { code: 'ha', label: 'Hausa', native: 'Hausa' },
  { code: 'yo', label: 'Yoruba', native: 'Yoruba' },
  { code: 'ig', label: 'Igbo', native: 'Igbo' },
  { code: 'zu', label: 'Zulu', native: 'Zulu' },
  { code: 'xh', label: 'Xhosa', native: 'Xhosa' },
  { code: 'am', label: 'Amharic', native: 'Amharic' },
  { code: 'ff', label: 'Fulani', native: 'Fulani' },
  { code: 'bm', label: 'Bambara', native: 'Bambara' },
  { code: 'ln', label: 'Lingala', native: 'Lingála' },
  { code: 'rw', label: 'Kinyarwanda', native: 'Kinyarwanda' },
  { code: 'ny', label: 'Chichewa', native: 'Nyanja' },
  { code: 'wo', label: 'Wolof', native: 'Wolof' },
  { code: 'ak', label: 'Akan', native: 'Akan' },
  { code: 'ee', label: 'Ewe', native: 'Ewe' },
  { code: 'gaa', label: 'Ga', native: 'Ga' },
  { code: 'ber', label: 'Berber', native: 'Tamazight' },
  // Americas
  { code: 'es-MX', label: 'Spanish (Mexican)', native: 'Español (Mexicano)' },
  { code: 'es-AR', label: 'Spanish (Argentina)', native: 'Español (Argentina)' },
  { code: 'es-CL', label: 'Spanish (Chilean)', native: 'Español (Chileno)' },
  { code: 'es-CO', label: 'Spanish (Colombian)', native: 'Español (Colombiano)' },
  { code: 'ht', label: 'Haitian Creole', native: 'Kreyòl Ayisyen' },
  { code: 'gn', label: 'Guarani', native: 'Guarani' },
  { code: 'quc', label: 'Maya (K\'iche\')', native: 'Maya K\'iche\'' },
  { code: 'kek', label: 'Maya (Q\'eqchi\')', native: 'Maya Q\'eqchi\'' },
  { code: 'nah', label: 'Nahuatl', native: 'Nahuatl' },
  { code: 'ay', label: 'Aymara', native: 'Aymara' },
];
