// Comprehensive Tarot Deck Data (All 78 Cards: 22 Major Arcana + 56 Minor Arcana)
// Complete with bilingual insights, keywords, upright meanings, position-specific readings, love, career, health, advice, and yes/no answers.

export interface TarotCardDetails {
  id: string;
  name: string;
  nameHi: string;
  arcana: 'Major' | 'Minor';
  suit: 'Major' | 'Cups' | 'Wands' | 'Swords' | 'Pentacles';
  rank: string;
  numeral: string;
  element: 'Fire' | 'Water' | 'Air' | 'Earth' | 'Spirit';
  elementHi: string;
  astrology: string;
  astrologyHi: string;
  yesNo: string;
  yesNoHi: string;
  essence: string;
  essenceHi: string;
  keywords: string[];
  keywordsHi: string[];
  uprightMeaning: string;
  uprightMeaningHi: string;
  pastMeaning: string;
  pastMeaningHi: string;
  presentMeaning: string;
  presentMeaningHi: string;
  futureMeaning: string;
  futureMeaningHi: string;
  love: string;
  loveHi: string;
  career: string;
  careerHi: string;
  health: string;
  healthHi: string;
  advice: string;
  adviceHi: string;
  symbolism: string;
  symbolismHi: string;
  icon: string;
  colorGradient: string;
  accentBorder: string;
}

export const TAROT_CARDS_DATA: Record<string, TarotCardDetails> = {
  // ===================== MAJOR ARCANA (22 CARDS) =====================
  "the fool": {
    id: "the-fool",
    name: "The Fool",
    nameHi: "द फूल (मूर्ख / निष्कपट साधक)",
    arcana: "Major",
    suit: "Major",
    rank: "0",
    numeral: "0",
    element: "Air",
    elementHi: "वायु (Air)",
    astrology: "Uranus / Air",
    astrologyHi: "यूरेनस / वायु तत्व",
    yesNo: "Yes",
    yesNoHi: "हाँ (Yes)",
    essence: "A leap of faith, new beginnings, unlimited potential, and spontaneous adventure.",
    essenceHi: "विश्वास की छलांग, नई शुरुआत, असीम संभावनाएं और सहज रोमांच।",
    keywords: ["New Beginnings", "Innocence", "Spontaneity", "Free Spirit", "Faith"],
    keywordsHi: ["नई शुरुआत", "निर्दोषता", "सहजता", "मुक्त आत्मा", "विश्वास"],
    uprightMeaning: "The Fool signifies the start of a profound spiritual or worldly journey. You stand on the precipice of something thrilling. Trust the universe, let go of fears, and embrace the unknown with wonder.",
    uprightMeaningHi: "द फूल एक गहरी आध्यात्मिक या सांसारिक यात्रा की शुरुआत का प्रतीक है। आप कुछ रोमांचक के मुहाने पर हैं। ब्रह्मांड पर विश्वास करें और निडर होकर आगे बढ़ें।",
    pastMeaning: "A past leap of faith or unconventional choice has paved the way to where you stand today.",
    pastMeaningHi: "अतीत में आपके द्वारा उठाए गए किसी साहसी कदम ने आज की परिस्थिति की नींव रखी है।",
    presentMeaning: "You are being offered a fresh start. Step forward boldly without overthinking or letting fear hold you back.",
    presentMeaningHi: "आपको एक नई शुरुआत का अवसर मिल रहा है। बिना हिचकिचाहट के उत्साह के साथ कदम आगे बढ़ाएं।",
    futureMeaning: "An exciting new chapter and unexpected adventures lie ahead. Embrace novelty with an open heart.",
    futureMeaningHi: "आगे एक रोमांचक नया अध्याय और अप्रत्याशित अवसर आपका इंतजार कर रहे हैं।",
    love: "Spontaneous romance, a fresh spark, or meeting someone who expands your world.",
    loveHi: "सहज और नया रोमांस, ताजगी भरा संबंध या किसी स्वतंत्र विचार वाले साथी से मुलाकात।",
    career: "Exciting new projects, entrepreneurial ventures, or exploring an unconventional career path.",
    careerHi: "नए प्रोजेक्ट्स की शुरुआत, स्टार्टअप या लीक से हटकर नए रास्ते तलाशना।",
    health: "Vitality, renewed energy, and refreshing your daily wellness routines.",
    healthHi: "नई ऊर्जा और ताजगी, दिनचर्या में नए स्वस्थ बदलाव का समय।",
    advice: "Take that leap of faith! Do not let fear of the unknown paralyze your spirit.",
    adviceHi: "हिम्मत करके आगे बढ़ें! अज्ञात के डर से अपने उत्साह को न रोकें।",
    symbolism: "The cliff edge represents taking risks; the white rose symbolizes pure intentions; the small dog signifies loyalty and warning instincts.",
    symbolismHi: "पहाड़ की चोटी जोखिम का प्रतीक है; सफेद गुलाब पवित्रता का और साथ में कुत्ता निष्ठा व अंतर्ज्ञान का सूचक है।",
    icon: "🤹",
    colorGradient: "from-amber-500/20 via-sky-500/20 to-purple-500/20",
    accentBorder: "border-amber-400"
  },
  "the magician": {
    id: "the-magician",
    name: "The Magician",
    nameHi: "द मैजिशियन (जादूगर / सृष्टिकर्ता)",
    arcana: "Major",
    suit: "Major",
    rank: "1",
    numeral: "I",
    element: "Air",
    elementHi: "वायु (Air)",
    astrology: "Mercury / Communication",
    astrologyHi: "बुध ग्रह / संचार व बुद्धि",
    yesNo: "Strong Yes",
    yesNoHi: "दृढ़ हाँ (Strong Yes)",
    essence: "Manifestation, resourcefulness, willpower, and turning ideas into tangible reality.",
    essenceHi: "मनोकामना पूर्ति, संसाधन कुशलता, इच्छाशक्ति और विचारों को वास्तविकता में बदलना।",
    keywords: ["Manifestation", "Power", "Resourcefulness", "Skill", "Action"],
    keywordsHi: ["प्रकटीकरण", "आत्मशक्ति", "संसाधन", "कौशल", "सक्रियता"],
    uprightMeaning: "You possess all the tools (Cup, Wand, Sword, Pentacle) needed to manifest your dreams into physical reality. Channel your willpower and focused intent.",
    uprightMeaningHi: "आपके पास अपने सपनों को सच करने के लिए सभी साधन और योग्यता मौजूद है। अपनी इच्छाशक्ति और एकाग्रता का उपयोग करें।",
    pastMeaning: "Past skills, mastery, or a conscious decision have given you current leverage and capability.",
    pastMeaningHi: "अतीत में सीखे गए कौशल और मेहनत आज आपकी सफलता की सबसे बड़ी ताकत हैं।",
    presentMeaning: "Now is the time for decisive action. Your creative and communicative powers are at their peak.",
    presentMeaningHi: "यह ठोस कदम उठाने का सही समय है। आपकी रचनात्मक और संवाद क्षमता शिखर पर है।",
    futureMeaning: "You will achieve successful manifestation and master your domain through focused action.",
    futureMeaningHi: "निरंतर प्रयास से आप अपने लक्ष्यों को सफलतापूर्वक साकार कर लेंगे।",
    love: "Magnetic attraction, dynamic connection, and taking the initiative in love.",
    loveHi: "आकर्षक व्यक्तित्व, रिश्तों में नई ऊर्जा और बातचीत से दूरियां मिटाना।",
    career: "Leadership, launching projects, turning creative concepts into profitable results.",
    careerHi: "नेतृत्व क्षमता, नए प्रोजेक्ट की शुरुआत और विचारों को मुनाफे में बदलना।",
    health: "Strong mental focus, vitality, and taking active charge of your body's wellness.",
    healthHi: "उत्कृष्ट मानसिक स्पष्टता, मजबूत जीवन शक्ति और स्वास्थ्य में सुधार।",
    advice: "Harness your inner power and act now. You have everything you need.",
    adviceHi: "अपनी क्षमताओं पर भरोसा करें और तुरंत शुरुआत करें। आपके पास सब कुछ है।",
    symbolism: "The infinity symbol (lemniscate) above the head represents infinite potential; table with 4 suit tools represents mastery over the elements.",
    symbolismHi: "अनंत का प्रतीक (∞) असीमित क्षमता को और मेज पर रखे चार उपकरण चारों तत्वों पर नियंत्रण को दर्शाते हैं।",
    icon: "🪄",
    colorGradient: "from-amber-600/20 via-yellow-500/20 to-indigo-600/20",
    accentBorder: "border-yellow-400"
  },
  "the high priestess": {
    id: "the-high-priestess",
    name: "The High Priestess",
    nameHi: "द हाई प्रीस्टेस (उच्च पुजारिन / अंतर्ज्ञान)",
    arcana: "Major",
    suit: "Major",
    rank: "2",
    numeral: "II",
    element: "Water",
    elementHi: "जल (Water)",
    astrology: "Moon / Intuition",
    astrologyHi: "चंद्रमा / अंतर्ज्ञान व रहस्य",
    yesNo: "Maybe",
    yesNoHi: "संभवतः / अंतर्मन की सुनें (Maybe)",
    essence: "Intuition, sacred secrets, the subconscious mind, and divine feminine wisdom.",
    essenceHi: "आंतरिक अंतर्ज्ञान, गुप्त ज्ञान, अवचेतन मन और दैवीय प्रज्ञा।",
    keywords: ["Intuition", "Mystery", "Subconscious", "Inner Wisdom", "Patience"],
    keywordsHi: ["अंतर्ज्ञान", "रहस्य", "अवचेतन", "आत्मज्ञान", "धैर्य"],
    uprightMeaning: "Look beyond the surface. Answers lie within your intuition, dreams, and quiet contemplation. Trust your gut feelings rather than relying solely on cold logic.",
    uprightMeaningHi: "बाहरी शोर से परे अपने अंतर्मन की आवाज सुनें। सपनों और मौन में छिपे संदेशों को पहचानें।",
    pastMeaning: "A past lesson in trusting your instincts or uncovering a hidden truth has shaped your wisdom.",
    pastMeaningHi: "अतीत के किसी अनुभव ने आपके अंतर्ज्ञान और अंतर्दृष्टि को गहरा किया है।",
    presentMeaning: "Be still and observe. Not all facts are visible yet; wait for hidden insights to reveal themselves.",
    presentMeaningHi: "धैर्य रखें और निरीक्षण करें। सभी बातें अभी सामने नहीं हैं; सही समय पर रहस्य खुलेंगे।",
    futureMeaning: "Deep spiritual awakening, unlocking esoteric mysteries, and trusting your higher self.",
    futureMeaningHi: "आध्यात्मिक जागृति और गुप्त ज्ञान की प्राप्ति होगी। अपने आत्मबल पर विश्वास रखें।",
    love: "Deep soulmate connection, unspoken emotional resonance, and patience in love.",
    loveHi: "गहरा आत्मिक जुड़ाव, बिना कहे एक-दूसरे को समझना और रिश्तों में गहरा भावनात्मक संबंध।",
    career: "Rely on research, strategy, and gut instincts before signing contracts or making big shifts.",
    careerHi: "जल्दबाजी के बजाय शोध, रणनीति और अंतर्ज्ञान के आधार पर पेशेवर निर्णय लें।",
    health: "Hormonal balance, mental peace, meditation, and listening to bodily cues.",
    healthHi: "मानसिक शांति, ध्यान और शरीर के सूक्ष्म संकेतों को समझना।",
    advice: "Listen to your inner voice. In quiet reflection, you will find total clarity.",
    adviceHi: "अपने अंतर्मन की आवाज सुनें। शांत रहकर ही आपको सबसे स्पष्ट उत्तर मिलेगा।",
    symbolism: "Pillars of Boaz and Jachin represent duality; the veil of pomegranates protects sacred mysteries; crescent moon at feet.",
    symbolismHi: "काले और सफेद खंभे द्वंद्व का प्रतीक हैं; अनार का पर्दा गुप्त रहस्यों का और चरणों में अर्धचंद्र अंतर्ज्ञान का सूचक है।",
    icon: "🔮",
    colorGradient: "from-blue-900/30 via-indigo-900/30 to-purple-900/30",
    accentBorder: "border-cyan-400"
  },
  "the empress": {
    id: "the-empress",
    name: "The Empress",
    nameHi: "द एम्प्रेस (महारानी / उर्वरता व समृद्धि)",
    arcana: "Major",
    suit: "Major",
    rank: "3",
    numeral: "III",
    element: "Earth",
    elementHi: "पृथ्वी (Earth)",
    astrology: "Venus / Love & Beauty",
    astrologyHi: "शुक्र ग्रह / प्रेम, सौंदर्य व समृद्धि",
    yesNo: "Strong Yes",
    yesNoHi: "दृढ़ हाँ (Strong Yes)",
    essence: "Abundance, fertility, nurturing energy, creative birth, and unconditional love.",
    essenceHi: "प्रचुरता, उर्वरता, पोषणकारी ऊर्जा, रचनात्मक सृजन और अटूट प्रेम।",
    keywords: ["Abundance", "Fertility", "Creativity", "Nurturing", "Sensuality"],
    keywordsHi: ["समृद्धि", "उर्वरता", "रचनात्मकता", "पोषण", "सौंदर्य"],
    uprightMeaning: "The Empress heralds a fertile season of growth, prosperity, artistic expression, and loving nourishment. Your projects, relationships, and wellbeing are blossoming.",
    uprightMeaningHi: "द एम्प्रेस समृद्धि, सुख, रचनात्मक विस्तार और रिश्तों में प्रेम का संकेत देती है। आपकी मेहनत रंग ला रही है।",
    pastMeaning: "A foundation built on care, love, and steady nurturing is now yielding sweet fruits.",
    pastMeaningHi: "अतीत में दिए गए प्यार और निरंतर देखरेख का आज शुभ परिणाम मिल रहा है।",
    presentMeaning: "Embrace comfort, beauty, and generosity. Create, nourish, and treat yourself with kindness.",
    presentMeaningHi: "रचनात्मकता और प्रेम को अपनाएं। अपने जीवन और आस-पास के लोगों का पोषण करें।",
    futureMeaning: "Great abundance, financial harmony, family happiness, and thriving creative projects.",
    futureMeaningHi: "आने वाले समय में सुख-समृद्धि, पारिवारिक शांति और नए सुखद अवसर मिलेंगे।",
    love: "Warmth, unconditional affection, marriage, deep intimacy, and potential childbirth/growth.",
    loveHi: "सच्चा प्रेम, प्रगाढ़ संबंध, विवाह और परिवार में खुशियों का आगमन।",
    career: "Thriving business, fruitful creative ventures, and a supportive, harmonious work culture.",
    careerHi: "व्यापार में वृद्धि, रचनात्मक कार्यों में लाभ और कार्यक्षेत्र में मान-सम्मान।",
    health: "Vitality, natural healing, healthy nourishment, and physical comfort.",
    healthHi: "उत्तम स्वास्थ्य, प्राकृतिक उपचार और मानसिक व शारीरिक संतुलन।",
    advice: "Nurture your creations and yourself with love, patience, and gratitude.",
    adviceHi: "अपने सपनों और स्वयं को प्यार और धैर्य से संवारें।",
    symbolism: "Crown of twelve stars represents the zodiac; wheat field represents harvest and fertility; waterfall symbolizes flowing emotions.",
    symbolismHi: "12 तारों का मुकुट 12 राशियों का, गेहूं का खेत समृद्धि का और झरना बहती हुई भावनाओं का प्रतीक है।",
    icon: "👑",
    colorGradient: "from-emerald-900/30 via-teal-900/30 to-amber-900/30",
    accentBorder: "border-emerald-400"
  },
  "the emperor": {
    id: "the-emperor",
    name: "The Emperor",
    nameHi: "द एम्परर (सम्राट / अनुशासन व सत्ता)",
    arcana: "Major",
    suit: "Major",
    rank: "4",
    numeral: "IV",
    element: "Fire",
    elementHi: "अग्नि (Fire)",
    astrology: "Aries / Mars",
    astrologyHi: "मेष राशि / मंगल ग्रह",
    yesNo: "Yes",
    yesNoHi: "हाँ (Yes)",
    essence: "Authority, structure, strategic leadership, discipline, and solid foundations.",
    essenceHi: "अधिकार, अनुशासन, रणनीतिक नेतृत्व और मजबूत आधारशिला।",
    keywords: ["Authority", "Structure", "Control", "Leadership", "Discipline"],
    keywordsHi: ["सत्ता", "संरचना", "अनुशासन", "नेतृत्व", "स्थायित्व"],
    uprightMeaning: "The Emperor calls for order, discipline, and assertive leadership. Build solid structures, establish clear boundaries, and lead your life with wisdom and conviction.",
    uprightMeaningHi: "द एम्परर अनुशासन, व्यवस्था और दृढ़ नेतृत्व की मांग करता है। स्पष्ट नियम बनाएं और अपने जीवन की बागडोर संभालें।",
    pastMeaning: "A mentor, father figure, or past disciplined effort created your current stability.",
    pastMeaningHi: "अतीत में किसी मार्गदर्शक या आपके कड़े अनुशासन ने आपको यह स्थिरता दी है।",
    presentMeaning: "Take charge of your situation with calm authority, strategic planning, and rational thinking.",
    presentMeaningHi: "स्थितियों का नियंत्रण अपने हाथ में लें। शांत दिमाग और योजनाबद्ध तरीके से आगे बढ़ें।",
    futureMeaning: "You will establish firm control, high respect, and long-term security in your domain.",
    futureMeaningHi: "आपको अपने कार्यक्षेत्र में सम्मान, अधिकार और दीर्घकालिक सुरक्षा प्राप्त होगी।",
    love: "Committed, protective, and stable partnership with clear mutual respect.",
    loveHi: "सुरक्षित, स्थिर और जिम्मेदार प्रेम संबंध जहां परस्पर सम्मान सर्वोपरि है।",
    career: "Executive roles, promotions, organizing systems, and authoritative business management.",
    careerHi: "पदोन्नति, प्रबंधन में सफलता, मजबूत व्यावसायिक नीतियां और अधिकार।",
    health: "Routine, structured exercise, posture, and managing stress through discipline.",
    healthHi: "नियमित व्यायाम, दिनचर्या का पालन और तनाव से मुक्ति के लिए व्यवस्थित जीवनशैली।",
    advice: "Step up as the leader of your destiny. Bring order and clarity to chaos.",
    adviceHi: "अपने भाग्य के स्वामी बनें। अव्यवस्था को समाप्त कर अनुशासन स्थापित करें।",
    symbolism: "Stone throne with ram heads signifies Aries; orb and scepter represent worldly dominion and rightful rule.",
    symbolismHi: "मेढ़े के सिर वाला पत्थर का सिंहासन मेष राशि का और राजदंड व चक्र सांसारिक अधिकार के प्रतीक हैं।",
    icon: "🏛️",
    colorGradient: "from-red-950/30 via-amber-950/30 to-slate-900/30",
    accentBorder: "border-red-500"
  },
  "the hierophant": {
    id: "the-hierophant",
    name: "The Hierophant",
    nameHi: "द हायरोफैंट (गुरु / परंपरा व ज्ञान)",
    arcana: "Major",
    suit: "Major",
    rank: "5",
    numeral: "V",
    element: "Earth",
    elementHi: "पृथ्वी (Earth)",
    astrology: "Taurus / Wisdom",
    astrologyHi: "वृषभ राशि / पारंपरिक ज्ञान",
    yesNo: "Yes",
    yesNoHi: "हाँ (Yes)",
    essence: "Spiritual wisdom, mentorship, sacred tradition, ethics, and structured learning.",
    essenceHi: "आध्यात्मिक ज्ञान, गुरु का मार्गदर्शन, पवित्र परंपरा और उच्च शिक्षा।",
    keywords: ["Tradition", "Spiritual Wisdom", "Mentorship", "Ethics", "Beliefs"],
    keywordsHi: ["परंपरा", "गुरु ज्ञान", "नैतिकता", "विश्वास", "शिक्षा"],
    uprightMeaning: "Seek established wisdom, trusted teachers, or proven principles. Align yourself with integrity, honor sacred commitments, and embrace deep learning.",
    uprightMeaningHi: "अनुभवी गुरुओं और स्थापित सिद्धांतों से मार्गदर्शन लें। नैतिकता और वचनों का पालन करें।",
    pastMeaning: "Traditional education, family roots, or a spiritual mentor gave you your moral compass.",
    pastMeaningHi: "पारिवारिक संस्कारों और गुरु की शिक्षा ने आपके दृष्टिकोण को दिशा दी है।",
    presentMeaning: "Seek advice from experts or join a community of shared values. Follow ethical protocols.",
    presentMeaningHi: "विशेषज्ञों से सलाह लें और सही नैतिक रास्ते का चयन करें।",
    futureMeaning: "Formal recognition, deeper spiritual clarity, or committing to a sacred institution.",
    futureMeaningHi: "आध्यात्मिक उत्थान, औपचारिक मान्यता या विवाह जैसे पवित्र बंधन का संकेत।",
    love: "Traditional marriage, deep values alignment, commitment, and mutual respect.",
    loveHi: "पारंपरिक विवाह, साझा संस्कार और एक-दूसरे के प्रति गहरी वफादारी।",
    career: "Working in reputable institutions, mentoring others, or succeeding through structured teamwork.",
    careerHi: "प्रतिष्ठित संस्थाओं में काम, शिक्षण, और स्थापित नियमों के साथ कार्य सिद्धि।",
    health: "Holistic traditional healing, ayurvedic or proven medical therapies.",
    healthHi: "पारंपरिक चिकित्सा पद्धतियां, योग और प्राकृतिक जीवनशैली।",
    advice: "Honor tradition and seek the counsel of wise mentors before making major moves.",
    adviceHi: "वरिष्ठों और गुरुजनों का मार्गदर्शन लें और सत्य के मार्ग पर चलें।",
    symbolism: "Triple cross represents the Holy Trinity / three realms; crossed golden keys unlock conscious and subconscious knowledge.",
    symbolismHi: "त्रिशूल रूपी क्रॉस तीनों लोकों का और दो सुनहरी चाबियां ज्ञान के द्वारों के खुलने का प्रतीक हैं।",
    icon: "📿",
    colorGradient: "from-amber-900/30 via-yellow-900/30 to-stone-900/30",
    accentBorder: "border-amber-500"
  },
  "the lovers": {
    id: "the-lovers",
    name: "The Lovers",
    nameHi: "द लवर्स (प्रेमी / आत्मिक मिलन व चुनाव)",
    arcana: "Major",
    suit: "Major",
    rank: "6",
    numeral: "VI",
    element: "Air",
    elementHi: "वायु (Air)",
    astrology: "Gemini / Duality & Union",
    astrologyHi: "मिथुन राशि / मिलन व चयन",
    yesNo: "Strong Yes",
    yesNoHi: "दृढ़ हाँ (Strong Yes)",
    essence: "Unconditional love, soulmate union, moral choices, and harmony of opposites.",
    essenceHi: "सच्चा प्रेम, आत्मिक मिलन, महत्वपूर्ण नैतिक चुनाव और सामंजस्य।",
    keywords: ["Love", "Harmony", "Relationships", "Values Choice", "Union"],
    keywordsHi: ["प्रेम", "सामंजस्य", "संबंध", "नैतिक चुनाव", "एकता"],
    uprightMeaning: "The Lovers signifies deep emotional connection, mutual attraction, and aligning with your highest personal values when faced with an important life crossroads.",
    uprightMeaningHi: "द लवर्स गहरे प्रेम, आत्मिक मेल और जीवन के किसी महत्वपूर्ण मोड़ पर दिल की सही राह चुनने का प्रतीक है।",
    pastMeaning: "A meaningful relationship or heartfelt choice in the past has defined your present values.",
    pastMeaningHi: "अतीत के किसी महत्वपूर्ण रिश्ते या निर्णय ने आपके आज के विचारों को गढ़ा है।",
    presentMeaning: "You are experiencing great alignment or facing a choice where your heart and values must lead.",
    presentMeaningHi: "आप एक गहरे संबंध में हैं या किसी ऐसे चुनाव के सामने हैं जहाँ दिल की सुनना जरूरी है।",
    futureMeaning: "A harmonious soulmate partnership, deep reconciliation, and lifelong emotional fulfillment.",
    futureMeaningHi: "सच्चे साथी का मिलन, संबंधों में मधुरता और जीवन में प्रेम की पूर्णता।",
    love: "Soulmate connection, profound mutual vulnerability, passionate romance, and true harmony.",
    loveHi: "सच्चा आत्मिक प्यार, अटूट विश्वास, भावनात्मक जुड़ाव और विवाह के योग।",
    career: "Favorable business partnerships, finding career callings aligned with your true passions.",
    careerHi: "सफल व्यापारिक साझेदारी और अपने मनपसंद काम में अपार सफलता।",
    health: "Mind-body harmony, emotional wellbeing, and healing through loving support.",
    healthHi: "भावनात्मक संतुलन और खुशहाल मन से शारीरिक स्वास्थ्य में सुधार।",
    advice: "Choose what resonates with your deepest truth and heart, not just superficial gains.",
    adviceHi: "वही रास्ता चुनें जो आपके दिल और आत्मा को संतुष्टि दे।",
    symbolism: "Archangel Raphael blesses the union; Tree of Life and Tree of Knowledge represent consciousness and choice.",
    symbolismHi: "देवदूत राफेल का आशीर्वाद, जीवन का वृक्ष और ज्ञान का वृक्ष आत्मिक संतुलन को दर्शाते हैं।",
    icon: "💖",
    colorGradient: "from-rose-900/30 via-pink-900/30 to-purple-900/30",
    accentBorder: "border-pink-400"
  },
  "the chariot": {
    id: "the-chariot",
    name: "The Chariot",
    nameHi: "द चैरियट (रथ / विजय व संकल्प)",
    arcana: "Major",
    suit: "Major",
    rank: "7",
    numeral: "VII",
    element: "Water",
    elementHi: "जल (Water)",
    astrology: "Cancer / Determination",
    astrologyHi: "कर्क राशि / दृढ़ संकल्प",
    yesNo: "Strong Yes",
    yesNoHi: "दृढ़ हाँ (Strong Yes)",
    essence: "Triumph through willpower, overcoming obstacles, focus, and drive toward victory.",
    essenceHi: "इच्छाशक्ति से विजय, बाधाओं को पार करना, एकाग्रता और लक्ष्य प्राप्ति।",
    keywords: ["Victory", "Willpower", "Drive", "Determination", "Overcoming"],
    keywordsHi: ["विजय", "इच्छाशक्ति", "दृढ़ संकल्प", "एकाग्रता", "प्रगति"],
    uprightMeaning: "Through disciplined focus and unshakeable resolve, you will conquer opposing forces and steer your chariot straight toward victorious breakthrough.",
    uprightMeaningHi: "अपने अटूट संकल्प और एकाग्रता से आप सभी कठिनाइयों को पार करके विजय प्राप्त करेंगे।",
    pastMeaning: "Past discipline and grit helped you overcome steep hurdles and gain momentum.",
    pastMeaningHi: "अतीत के आपके कड़े परिश्रम और आत्मविश्वास ने आपको आज इस मुकाम पर पहुंचाया है।",
    presentMeaning: "Harness your conflicting thoughts or external challenges. Stay focused on your primary goal.",
    presentMeaningHi: "विरोधी परिस्थितियों पर नियंत्रण रखें और केवल अपने मुख्य लक्ष्य पर ध्यान केंद्रित करें।",
    futureMeaning: "Decisive triumph, rapid progress, successful travel, and achieving your ambition.",
    futureMeaningHi: "निश्चित विजय, तेज गति से प्रगति और महत्वाकांक्षाओं की पूर्ति होगी।",
    love: "Overcoming relationship challenges together; taking active steps toward shared goals.",
    loveHi: "रिश्ते की चुनौतियों पर विजय और साथ मिलकर आगे बढ़ने का संकल्प।",
    career: "Career breakthroughs, winning competitive bids, rapid promotion, and business expansion.",
    careerHi: "कैरियर में बड़ी उपलब्धि, प्रतियोगिता में जीत और तेजी से आगे बढ़ना।",
    health: "High stamina, physical fitness, rehabilitation victory, and disciplined training.",
    healthHi: "उच्च ऊर्जा, शारीरिक सहनशक्ति और नियमित व्यायाम से स्वास्थ्य लाभ।",
    advice: "Keep your eyes on the prize. Steer your emotions with firm resolve.",
    adviceHi: "अपने लक्ष्य पर नजर बनाए रखें। भावनाओं को सही दिशा देकर आगे बढ़ें।",
    symbolism: "Black and white sphinxes represent opposing forces mastered by the rider's mind; star canopy represents celestial protection.",
    symbolismHi: "काले और सफेद स्फिंक्स विपरीत परिस्थितियों पर नियंत्रण को और सितारों की छतरी दैवीय सुरक्षा को दर्शाती है।",
    icon: "🏹",
    colorGradient: "from-amber-800/30 via-indigo-900/30 to-blue-950/30",
    accentBorder: "border-amber-400"
  },
  "strength": {
    id: "strength",
    name: "Strength",
    nameHi: "स्ट्रेंथ (बल / आत्मसंयम व कोमल साहस)",
    arcana: "Major",
    suit: "Major",
    rank: "8",
    numeral: "VIII",
    element: "Fire",
    elementHi: "अग्नि (Fire)",
    astrology: "Leo / Courage",
    astrologyHi: "सिंह राशि / आंतरिक साहस",
    yesNo: "Strong Yes",
    yesNoHi: "दृढ़ हाँ (Strong Yes)",
    essence: "Inner courage, gentle persuasion, self-mastery, compassion, and resilience.",
    essenceHi: "आंतरिक साहस, कोमलता से विजय, आत्म-नियंत्रण, करुणा और धैर्य।",
    keywords: ["Courage", "Compassion", "Patience", "Inner Strength", "Self-Mastery"],
    keywordsHi: ["साहस", "करुणा", "धैर्य", "आंतरिक बल", "संयम"],
    uprightMeaning: "True power is not brute force; it is calm patience, gentle love, and mastering your own primal impulses with compassion and grace.",
    uprightMeaningHi: "सच्ची शक्ति क्रोध या दबाव में नहीं, बल्कि शांत धैर्य, प्रेम और करुणा से परिस्थितियों को वश में करने में है।",
    pastMeaning: "A period of endurance and emotional resilience has forged your inner character.",
    pastMeaningHi: "अतीत के कठिन समय में दिखाए गए आपके धैर्य ने आपको बेहद मजबूत बनाया है।",
    presentMeaning: "Approach conflicts with kindness and composed confidence rather than aggressive reaction.",
    presentMeaningHi: "विवादों का सामना क्रोध के बजाय शांत आत्मविश्वास और समझदारी से करें।",
    futureMeaning: "You will successfully tame any fierce difficulty and emerge respected and peaceful.",
    futureMeaningHi: "आप बड़ी से बड़ी चुनौती को अपनी समझदारी और धीरज से हल कर लेंगे।",
    love: "Deep unconditional bonding, soothing emotional turbulence with affection and empathy.",
    loveHi: "प्रेम में समझदारी, एक-दूसरे की कमियों को अपनाना और रिश्ते में गहरा स्थायित्व।",
    career: "Persuasive leadership, managing difficult personalities gracefully, and steady career growth.",
    careerHi: "कठिन सहकर्मियों या परिस्थितियों को कुशलता से संभालना और कार्यक्षेत्र में प्रशंसा।",
    health: "Vitality recovery, boosting immune strength, and mental endurance.",
    healthHi: "रोग प्रतिरोधक क्षमता में वृद्धि, मानसिक मजबूती और त्वरित स्वास्थ्य लाभ।",
    advice: "Lead with love and quiet fortitude. Gentleness will conquer where aggression fails.",
    adviceHi: "विनम्रता और अटूट धैर्य रखें। कोमलता वहां जीतती है जहां गुस्सा हार जाता है।",
    symbolism: "Woman gently closing lion's jaw shows love mastering raw instinct; infinity symbol above head represents spiritual endurance.",
    symbolismHi: "स्त्री द्वारा शेर के मुंह को प्यार से सहलाना दिखाता है कि प्रेम और संयम से हर शक्ति को वश में किया जा सकता है।",
    icon: "🦁",
    colorGradient: "from-amber-600/30 via-yellow-600/30 to-orange-900/30",
    accentBorder: "border-amber-400"
  },
  "the hermit": {
    id: "the-hermit",
    name: "The Hermit",
    nameHi: "द हर्मिट (संन्यासी / आत्ममंथन व प्रकाश)",
    arcana: "Major",
    suit: "Major",
    rank: "9",
    numeral: "IX",
    element: "Earth",
    elementHi: "पृथ्वी (Earth)",
    astrology: "Virgo / Inner Search",
    astrologyHi: "कन्या राशि / आत्मनिरीक्षण",
    yesNo: "Maybe / Pause",
    yesNoHi: "ठहरें व विचार करें (Pause)",
    essence: "Soul-searching, inner wisdom, solitude, seeking higher truth, and spiritual guidance.",
    essenceHi: "आत्म-अन्वेषण, आंतरिक ज्ञान, एकांत, सत्य की खोज और आध्यात्मिक मार्गदर्शन।",
    keywords: ["Soul Searching", "Solitude", "Wisdom", "Inner Light", "Guidance"],
    keywordsHi: ["आत्ममंथन", "एकांत", "आत्मज्ञान", "आंतरिक प्रकाश", "मार्गदर्शन"],
    uprightMeaning: "Step back from external noise. Solitude and introspection will reveal the profound answers and spiritual clarity you seek.",
    uprightMeaningHi: "बाहरी दुनिया की भागदौड़ से थोड़ा समय निकालकर स्वयं के साथ रहें। एकांत में ही आपको अपने सवालों के सही जवाब मिलेंगे।",
    pastMeaning: "A period of study, contemplation, or independence has given you rare discernment.",
    pastMeaningHi: "अतीत के आत्ममंथन और अध्ययन ने आपकी समझ को बहुत गहरा किया है।",
    presentMeaning: "Take quiet time to reflect on your path before taking the next major step.",
    presentMeaningHi: "कोई बड़ा निर्णय लेने से पहले शांत मन से आत्मनिरीक्षण करें।",
    futureMeaning: "You will discover your true calling and become a beacon of light and guidance for others.",
    futureMeaningHi: "आपको अपने जीवन का सच्चा उद्देश्य मिलेगा और आप दूसरों के लिए प्रेरणास्रोत बनेंगे।",
    love: "Self-discovery before dating, appreciating sacred alone-time, or finding a deeply mature partner.",
    loveHi: "खुद को समझना, रिश्ते में व्यक्तिगत स्वतंत्रता का सम्मान और परिपक्व साथी की तलाश।",
    career: "Specialized research, independent consulting, mentoring, or seeking meaningful purpose over money alone.",
    careerHi: "गहन अनुसंधान, स्वतंत्र कार्य, परामर्श और अर्थपूर्ण दिशा का चयन।",
    health: "Rest, meditation, mindfulness, detoxifying from digital clutter.",
    healthHi: "पर्याप्त विश्राम, ध्यान और मानसिक शांति के लिए स्क्रीन से दूरी।",
    advice: "Shine the lantern inward. Your own soul already knows the right answer.",
    adviceHi: "अपने भीतर झांकें। आपकी अंतरात्मा सही रास्ता पहले से जानती है।",
    symbolism: "Lantern containing a 6-pointed star of Solomon illuminates the truth; staff symbolizes authority of wisdom on the rugged path.",
    symbolismHi: "लालटेन में जलता छह कोनों वाला तारा ज्ञान के प्रकाश का और लाठी जीवन के कठिन मार्ग पर सहारे का प्रतीक है।",
    icon: "🕯️",
    colorGradient: "from-slate-800/40 via-indigo-950/40 to-slate-900/40",
    accentBorder: "border-slate-400"
  },
  "wheel of fortune": {
    id: "wheel-of-fortune",
    name: "Wheel of Fortune",
    nameHi: "व्हील ऑफ फॉर्च्यून (भाग्य चक्र / कर्म व परिवर्तन)",
    arcana: "Major",
    suit: "Major",
    rank: "10",
    numeral: "X",
    element: "Fire",
    elementHi: "अग्नि / भाग्य (Fire)",
    astrology: "Jupiter / Luck & Karma",
    astrologyHi: "बृहस्पति ग्रह / भाग्य व कर्म",
    yesNo: "Strong Yes",
    yesNoHi: "दृढ़ हाँ (Strong Yes)",
    essence: "Karmic turning point, good luck, destiny, inevitable cycles, and positive change.",
    essenceHi: "भाग्य का बदलना, शुभ अवसर, कर्मफल, जीवन के चक्र और अप्रत्याशित सफलता।",
    keywords: ["Good Luck", "Karma", "Destiny", "Life Cycles", "Turning Point"],
    keywordsHi: ["सौभाग्य", "कर्म", "भाग्य", "परिवर्तन", "नया मोड़"],
    uprightMeaning: "The cosmic wheel is turning in your favor. Expect sudden breakthroughs, favorable coincidences, and positive shifts in destiny.",
    uprightMeaningHi: "भाग्य का चक्र आपके पक्ष में घूम रहा है। अचानक सुखद बदलाव, नए अवसर और कर्मों का शुभ फल मिलने वाला है।",
    pastMeaning: "A past cycle of struggle has reached its completion, making way for upward movement.",
    pastMeaningHi: "कठिनाइयों का पुराना दौर समाप्त हो चुका है और अब उन्नति का समय आ गया है।",
    presentMeaning: "Seize unexpected opportunities as luck aligns with your prepared efforts right now.",
    presentMeaningHi: "सामने आ रहे नए अवसरों को तुरंत लपकें; भाग्य आपका साथ दे रहा है।",
    futureMeaning: "A major upturn in fortunes, karmic rewards, and joyful life transformations.",
    futureMeaningHi: "भाग्य में शानदार वृद्धि, लंबे समय से रुके कार्यों का पूरा होना और नई खुशियां।",
    love: "Serendipitous meetings, karmic love connections, and relationships leveling up positively.",
    loveHi: "संयोग से किसी खास से मुलाकात, आत्मिक संबंध और रिश्ते में सुखद मोड़।",
    career: "Favorable windfalls, job offers, profitable investments, and positive career pivots.",
    careerHi: "अचानक धन लाभ, नई नौकरी का प्रस्ताव और व्यापार में बड़ी सफलता।",
    health: "Turnaround for the better, renewed vitality, and positive health developments.",
    healthHi: "स्वास्थ्य में तेज सुधार और ऊर्जावान महसूस करना।",
    advice: "Embrace the winds of change with gratitude. Flow with the cosmic cycle.",
    adviceHi: "बदलाव का खुले दिल से स्वागत करें और ईश्वर पर विश्वास रखें।",
    symbolism: "Hebrew letters YHVH (Tetragrammaton) and TARO/ROTA on wheel; four winged creatures in corners represent fixed astrological signs.",
    symbolismHi: "पहिए पर बने पवित्र अक्षर ब्रह्मांडीय नियमों को और चारों कोनों में मौजूद देवदूत चार दिशाओं और राशियों के संतुलन को दर्शाते हैं।",
    icon: "🎡",
    colorGradient: "from-amber-600/30 via-purple-900/30 to-indigo-950/30",
    accentBorder: "border-amber-400"
  },
  "justice": {
    id: "justice",
    name: "Justice",
    nameHi: "जस्टिस (न्याय / सत्य व संतुलन)",
    arcana: "Major",
    suit: "Major",
    rank: "11",
    numeral: "XI",
    element: "Air",
    elementHi: "वायु (Air)",
    astrology: "Libra / Fairness",
    astrologyHi: "तुला राशि / निष्पक्षता व न्याय",
    yesNo: "Yes (if fair)",
    yesNoHi: "हाँ, यदि न्यायसंगत हो (Yes)",
    essence: "Truth, fairness, karmic balance, accountability, and legal clarity.",
    essenceHi: "सत्य, निष्पक्षता, कर्मों का हिसाब, ईमानदारी और कानूनी स्पष्टता।",
    keywords: ["Justice", "Truth", "Fairness", "Karma", "Balance"],
    keywordsHi: ["न्याय", "सत्य", "निष्पक्षता", "संतुलन", "ईमानदारी"],
    uprightMeaning: "Truth and integrity will prevail. You are called to be honest, weigh all facts objectively, and expect fair outcomes in legal or moral matters.",
    uprightMeaningHi: "सत्य और निष्पक्षता की जीत होगी। सभी तथ्यों का ईमानदारी से विश्लेषण करें; आपके साथ न्याय होगा।",
    pastMeaning: "Past actions and ethical decisions are now bearing their direct, fair results.",
    pastMeaningHi: "अतीत के आपके सही आचरण और निर्णयों का उचित परिणाम अब सामने आ रहा है।",
    presentMeaning: "Stand firm in your truth. Make balanced decisions without emotional bias.",
    presentMeaningHi: "सत्य पर अडिग रहें। बिना किसी पक्षपात के संतुलित और निष्पक्ष निर्णय लें।",
    futureMeaning: "Favorable resolution of disputes, legal victories, and restoring equilibrium.",
    futureMeaningHi: "विवादों का शांतिपूर्ण समाधान, कानूनी मामलों में जीत और न्याय की स्थापना।",
    love: "Equal partnership, open honesty, signing marriage agreements, and fair mutual treatment.",
    loveHi: "समानता पर आधारित रिश्ता, स्पष्ट संवाद और विवाह के कानूनी या सामाजिक बंधन।",
    career: "Contract negotiations, fair compensation, settling agreements, and ethical success.",
    careerHi: "न्यायसंगत अनुबंध, सही मूल्यांकन और ईमानदारी से कार्यक्षेत्र में प्रतिष्ठा।",
    health: "Restoring bodily balance, healthy lifestyle adjustments, and moderation.",
    healthHi: "शारीरिक संतुलन और संयमित जीवनशैली से उत्तम स्वास्थ्य।",
    advice: "Act with absolute honesty and fairness. The scales of karma never miss.",
    adviceHi: "हमेशा सत्य और धर्म का साथ दें। कर्मों का फल अवश्य मिलता है।",
    symbolism: "Upright double-edged sword cuts through illusion; golden scales weigh evidence with impartiality.",
    symbolismHi: "दोधारी तलवार भ्रम को काटकर सत्य दिखाती है और तराजू निष्पक्ष न्याय का प्रतीक है।",
    icon: "⚖️",
    colorGradient: "from-blue-900/30 via-indigo-900/30 to-slate-900/30",
    accentBorder: "border-sky-400"
  },
  "the hanged man": {
    id: "the-hanged-man",
    name: "The Hanged Man",
    nameHi: "द हैंग्ड मैन (तपस्वी / नया दृष्टिकोण व समर्पण)",
    arcana: "Major",
    suit: "Major",
    rank: "12",
    numeral: "XII",
    element: "Water",
    elementHi: "जल (Water)",
    astrology: "Neptune / Surrender",
    astrologyHi: "नेपच्यून / समर्पण व त्याग",
    yesNo: "Wait / Pause",
    yesNoHi: "प्रतीक्षा करें (Wait)",
    essence: "Surrender, seeing things from a fresh angle, pause, letting go of control, and spiritual illumination.",
    essenceHi: "समर्पण, नए नजरिए से देखना, ठहराव, नियंत्रण छोड़ना और आत्म-बोध।",
    keywords: ["Surrender", "New Perspective", "Pause", "Letting Go", "Insight"],
    keywordsHi: ["समर्पण", "नया दृष्टिकोण", "ठहराव", "त्याग", "आत्म-बोध"],
    uprightMeaning: "Do not force outcomes right now. Surrender the need for control, view your challenges upside down from a completely new angle, and let illumination arise.",
    uprightMeaningHi: "जबरदस्ती चीजों को आगे बढ़ाने की कोशिश न करें। स्थिति को एक नए नजरिए से देखें और समर्पण का भाव रखें।",
    pastMeaning: "A past sacrifice or intentional pause has granted you profound patience and empathy.",
    pastMeaningHi: "अतीत में किए गए त्याग या धैर्य ने आपको गहरी अंतर्दृष्टि दी है।",
    presentMeaning: "Step back and suspend judgment. The apparent delay is serving your higher spiritual growth.",
    presentMeaningHi: "इस समय जल्दबाजी न करें। यह रुकावट आपके आत्म-विकास के लिए आवश्यक है।",
    futureMeaning: "A radical shift in mindset that dissolves old problems and brings deep enlightenment.",
    futureMeaningHi: "सोच में एक क्रांतिकारी बदलाव आएगा जो पुरानी सभी समस्याओं को हल कर देगा।",
    love: "Releasing ego, giving a partner space, and looking at relationships through selfless empathy.",
    loveHi: "अहंकार को छोड़ना, साथी को समय देना और निस्वार्थ प्रेम से रिश्ते को समझना।",
    career: "A temporary plateau; use this time to re-evaluate strategies and learn new methodologies.",
    careerHi: "व्यापार या नौकरी में ठहराव; इस समय का उपयोग नई योजनाएं बनाने में करें।",
    health: "Rest, gentle stretching, releasing mental tension, and emotional surrender.",
    healthHi: "तनाव मुक्ति, विश्राम और मानसिक शांति।",
    advice: "Let go of control. When you change how you look at things, what you look at changes.",
    adviceHi: "नियंत्रण की जिद छोड़ें। नजरिया बदलते ही परिस्थितियां बदल जाएंगी।",
    symbolism: "Halo of light around head indicates spiritual awakening despite physical suspension from the living wood tree.",
    symbolismHi: "सिर के चारों ओर का प्रभामंडल शारीरिक ठहराव के बावजूद आध्यात्मिक जागृति का प्रतीक है।",
    icon: "🧘",
    colorGradient: "from-cyan-950/30 via-blue-950/30 to-indigo-950/30",
    accentBorder: "border-cyan-400"
  },
  "death": {
    id: "death",
    name: "Death",
    nameHi: "डेथ (परिवर्तन / अंत व पुनर्जन्म)",
    arcana: "Major",
    suit: "Major",
    rank: "13",
    numeral: "XIII",
    element: "Water",
    elementHi: "जल (Water)",
    astrology: "Scorpio / Metamorphosis",
    astrologyHi: "वृश्चिक राशि / कायाकल्प व पुनर्जन्म",
    yesNo: "No (to old) / Yes (to new)",
    yesNoHi: "पुरातन का अंत, नए का आरंभ (Transformation)",
    essence: "Profound transformation, closing of an old cycle, shedding the past, and rebirth.",
    essenceHi: "गहरा कायाकल्प, पुराने अध्याय का अंत, अतीत से मुक्ति और नवजीवन की शुरुआत।",
    keywords: ["Transformation", "Endings", "Rebirth", "Transition", "New Era"],
    keywordsHi: ["परिवर्तन", "समाप्ति", "पुनर्जन्म", "संक्रमण", "नया युग"],
    uprightMeaning: "Death is not physical demise; it represents the inevitable, liberating end of a worn-out phase. Shed the past fearlessly to make room for glorious rebirth.",
    uprightMeaningHi: "यह कार्ड भौतिक मृत्यु नहीं बल्कि पुराने का अंत और नए का उदय दर्शाता है। जो छूट रहा है उसे जाने दें ताकि नया जीवन प्रवेश कर सके।",
    pastMeaning: "A major life closure or ending has cleared toxic debris from your path.",
    pastMeaningHi: "अतीत के किसी बड़े अंत ने आपके जीवन से नकारात्मकता को साफ किया है।",
    presentMeaning: "Release what no longer serves your soul. Accept inevitable transition with peace.",
    presentMeaningHi: "जो अब आपके विकास में सहायक नहीं है उसे छोड़ दें। बदलाव को शांति से स्वीकारें।",
    futureMeaning: "A brand-new lifestyle, fresh identity, and powerful renaissance rising from the ashes.",
    futureMeaningHi: "पुराने के समापन के बाद एक शानदार नए जीवन और पहचान की शुरुआत होगी।",
    love: "Ending unfulfilling patterns, transforming a relationship, or closing old ex-ties for true love.",
    loveHi: "पुरानी कड़वाहट का अंत, रिश्ते का नया रूप या नए सच्चे प्रेम का मार्ग प्रशस्त होना।",
    career: "Career transition, leaving stagnant jobs, phasing out old products for breakthrough innovations.",
    careerHi: "पुरानी नौकरी या नुकसानदेह व्यापार को छोड़कर नए सफल कार्यक्षेत्र की ओर बढ़ना।",
    health: "Detoxification, letting go of bad habits, rejuvenation, and cellular healing.",
    healthHi: "बुरी आदतों से मुक्ति, शरीर का डिटॉक्स और नया स्वास्थ्य लाभ।",
    advice: "Do not resist the ending. Clear the soil so new flowers can bloom.",
    adviceHi: "बदलाव का विरोध न करें। पुराने को विदा करें ताकि नया खिल सके।",
    symbolism: "Black armor represents invulnerability of change; white rose on black banner represents life and purification; rising sun between two towers.",
    symbolismHi: "सफेद गुलाब शुद्धता और जीवन का प्रतीक है, और दूर क्षितिज पर उगता सूरज पुनर्जन्म को दर्शाता है।",
    icon: "🌅",
    colorGradient: "from-stone-900/40 via-purple-950/40 to-slate-900/40",
    accentBorder: "border-purple-400"
  },
  "temperance": {
    id: "temperance",
    name: "Temperance",
    nameHi: "टेम्परेंस (संतुलन / संयम व सामंजस्य)",
    arcana: "Major",
    suit: "Major",
    rank: "14",
    numeral: "XIV",
    element: "Fire",
    elementHi: "अग्नि / सामंजस्य (Fire)",
    astrology: "Sagittarius / Balance",
    astrologyHi: "धनु राशि / संतुलन व समन्वय",
    yesNo: "Strong Yes",
    yesNoHi: "दृढ़ हाँ (Strong Yes)",
    essence: "Balance, moderation, alchemy, patient harmony, and healing integration.",
    essenceHi: "संतुलन, संयम, सामंजस्य, धैर्यपूर्वक एकीकरण और गहरा उपचार।",
    keywords: ["Balance", "Moderation", "Patience", "Harmony", "Healing"],
    keywordsHi: ["संतुलन", "संयम", "धैर्य", "सामंजस्य", "स्वास्थ्य"],
    uprightMeaning: "Find the golden middle way. Blend opposing energies with patience and calm grace. Healing and steady progress come through moderation.",
    uprightMeaningHi: "अति से बचें और संतुलन का मार्ग अपनाएं। धैर्य और संयम से हर विपरीत स्थिति में सामंजस्य स्थापित होगा।",
    pastMeaning: "Your calm moderation and diplomatic choices have maintained stability amidst past storms.",
    pastMeaningHi: "अतीत में आपके संतुलित व्यवहार ने बड़े विवादों को टालकर शांति बनाए रखी।",
    presentMeaning: "Practice patience. Avoid extreme reactions and integrate differing perspectives gently.",
    presentMeaningHi: "धैर्य रखें। किसी भी अतिवादी निर्णय से बचें और सब कुछ शांति से सुलझाएं।",
    futureMeaning: "Inner peace, complete emotional recovery, and harmonizing all life areas seamlessly.",
    futureMeaningHi: "जीवन में पूर्ण शांति, उत्तम स्वास्थ्य और सभी क्षेत्रों में गहरा संतुलन स्थापित होगा।",
    love: "Peaceful compatibility, mutual compromise, deep emotional healing, and enduring affection.",
    loveHi: "आपसी समझदारी, प्रेम में शांति, सुलह और एक-दूसरे के प्रति गहरा सम्मान।",
    career: "Successful collaboration, mediating disputes, sustainable long-term business growth.",
    careerHi: "टीम में बेहतर तालमेल, विवादों का हल और स्थिर व दीर्घकालिक प्रगति।",
    health: "Holistic wellness, balancing diet and exercise, recovery from illness.",
    healthHi: "संतुलित आहार, योग और जीवनशैली में सुधार से रोगों से मुक्ति।",
    advice: "Walk the middle path. Blend fire and water with serene alchemy.",
    adviceHi: "मध्यम मार्ग अपनाएं। शांति और समझदारी से हर समस्या का हल निकालें।",
    symbolism: "Angel pouring water between two cups symbolizes continuous alchemical flow; one foot on earth and one in water represents subconscious/conscious balance.",
    symbolismHi: "दो प्यालों के बीच जल का निरंतर प्रवाह ऊर्जा के संतुलन को और जल व भूमि पर पैर दोनों लोकों के सामंजस्य को दर्शाते हैं।",
    icon: "🕊️",
    colorGradient: "from-blue-900/30 via-amber-900/30 to-teal-900/30",
    accentBorder: "border-teal-400"
  },
  "the devil": {
    id: "the-devil",
    name: "The Devil",
    nameHi: "द डेविल (माया / बंधन व आसक्ति)",
    arcana: "Major",
    suit: "Major",
    rank: "15",
    numeral: "XV",
    element: "Earth",
    elementHi: "पृथ्वी (Earth)",
    astrology: "Capricorn / Materialism",
    astrologyHi: "मकर राशि / भौतिक आसक्ति",
    yesNo: "Caution / No",
    yesNoHi: "सावधानी / नहीं (Caution)",
    essence: "Breaking illusions, unhealthy attachments, materialism, shadow work, and liberating yourself from mental chains.",
    essenceHi: "भ्रम तोड़ना, अस्वास्थ्यकर आसक्ति, भौतिक मोह, छाया से मुक्ति और जंजीरों को काटना।",
    keywords: ["Shadow Self", "Attachment", "Illusion", "Obsession", "Liberation"],
    keywordsHi: ["मोह", "आसक्ति", "भ्रम", "बंधन", "मुक्ति"],
    uprightMeaning: "Recognize that the chains binding you are loose and self-imposed. Free yourself from toxic habits, fear, materialism, or codependency by claiming your power.",
    uprightMeaningHi: "पहचानें कि जिन बंधनों ने आपको जकड़ रखा है, वे आपके ही डर और आदतों से बने हैं। अपनी आत्मशक्ति पहचानें और बंधनों को तोड़ें।",
    pastMeaning: "A past addiction, obsession, or toxic environment has taught you hard-won discernment.",
    pastMeaningHi: "अतीत की किसी बुरी आदत या नकारात्मक परिस्थिति ने आपको सतर्क रहना सिखाया है।",
    presentMeaning: "Look closely at where you feel trapped. You actually have the freedom to walk away right now.",
    presentMeaningHi: "जहां आप खुद को फंसा हुआ महसूस कर रहे हैं, ध्यान से देखें—आप जब चाहें उस स्थिति से बाहर निकल सकते हैं।",
    futureMeaning: "Overcoming shadow addictions, reclaiming your autonomy, and shattering disempowering beliefs.",
    futureMeaningHi: "नकारात्मक आदतों और बंधनों पर विजय प्राप्त होगी और आप पूर्ण स्वतंत्रता हासिल करेंगे।",
    love: "Watch out for toxic codependency, possessiveness, or superficial physical obsessions.",
    loveHi: "रिश्तों में अत्यधिक अधिकार जताने, ईर्ष्या या अस्वस्थ निर्भरता से बचें।",
    career: "Beware of golden handcuffs, unethical temptations, or feeling trapped by a paycheck.",
    careerHi: "अनपेक्षित प्रलोभनों या अनैतिक समझौतों से बचें; अपनी स्वतंत्रता को प्राथमिकता दें।",
    health: "Detox from substance dependency, compulsive eating, or negative self-talk.",
    healthHi: "नशे या अस्वास्थ्यकर आदतों से दूरी बनाएं और मानसिक स्वास्थ्य पर ध्यान दें।",
    advice: "Take off the loose chains. Your enslavement is only an illusion of fear.",
    adviceHi: "अपने डर की बेड़ियों को उतार फेंकें। आप पूरी तरह स्वतंत्र हैं।",
    symbolism: "Loose chains around the couple's necks show they can step away anytime; inverted pentagram represents matter dominating spirit.",
    symbolismHi: "गले में ढीली जंजीरें दिखाती हैं कि व्यक्ति चाहे तो खुद को कभी भी इस बंधन से मुक्त कर सकता है।",
    icon: "⛓️",
    colorGradient: "from-red-950/40 via-stone-900/40 to-black/40",
    accentBorder: "border-red-600"
  },
  "the tower": {
    id: "the-tower",
    name: "The Tower",
    nameHi: "द टॉवर (अचानक परिवर्तन / भ्रम का टूटना)",
    arcana: "Major",
    suit: "Major",
    rank: "16",
    numeral: "XVI",
    element: "Fire",
    elementHi: "अग्नि (Fire)",
    astrology: "Mars / Sudden Shock",
    astrologyHi: "मंगल ग्रह / अप्रत्याशित आघात व शुद्धि",
    yesNo: "Caution / Disruptive",
    yesNoHi: "अचानक बदलाव (Disruptive)",
    essence: "Sudden awakening, destruction of false foundations, lightning breakthrough, and liberating truth.",
    essenceHi: "अचानक जागृति, झूठे आधार का ढहना, बिजली की तरह सत्य का प्रकटीकरण और मुक्ति।",
    keywords: ["Sudden Change", "Awakening", "Upheaval", "Truth", "Breakthrough"],
    keywordsHi: ["अचानक बदलाव", "जागृति", "उथल-पुथल", "सत्य", "मुक्ति"],
    uprightMeaning: "A sudden lightning bolt of truth shatters fragile illusions and unstable foundations. Though shocking, this breakdown clears the way for authentic reconstruction.",
    uprightMeaningHi: "सत्य का एक जोरदार झटका उन सभी चीजों को गिरा देता है जो झूठ पर टिकी थीं। यह बदलाव भले ही अप्रत्याशित हो, पर यह आपके भले के लिए है।",
    pastMeaning: "A past shock or sudden upheaval demolished what was fake, pushing you onto your true path.",
    pastMeaningHi: "अतीत के किसी अचानक बदलाव ने आपको भ्रम से निकालकर सच्चाई के रास्ते पर डाला।",
    presentMeaning: "Do not cling to collapsing structures. Let what must fall fall, and stand firm in your truth.",
    presentMeaningHi: "जो टूट रहा है उसे बचाने की व्यर्थ कोशिश न करें; नए निर्माण के लिए तैयार रहें।",
    futureMeaning: "A revolutionary awakening that wipes away stale stagnation and brings immense freedom.",
    futureMeaningHi: "एक क्रांतिकारी परिवर्तन जो पुराने बंधनों को मिटाकर जीवन में नई ऊर्जा भरेगा।",
    love: "Sudden reality check, breaking deceptive bonds, or explosive emotional breakthroughs.",
    loveHi: "संबंधों में सच्चाई का अचानक सामने आना और खोखले रिश्तों से मुक्ति।",
    career: "Restructuring, sudden shifts in company or industry, breaking out of stifling careers.",
    careerHi: "कार्यक्षेत्र में अचानक बदलाव, नई दिशा की ओर कदम और पुराने ढर्रे का टूटना।",
    health: "Sudden symptom alerts that force healthy changes, or energetic catharsis.",
    healthHi: "स्वास्थ्य के प्रति तुरंत सचेत होने की आवश्यकता, आराम और पुनरुद्धार।",
    advice: "Let the false walls tumble. What is built on truth can never be destroyed.",
    adviceHi: "झूठ की दीवारों को गिरने दें। जो सत्य है वह कभी नष्ट नहीं हो सकता।",
    symbolism: "Lightning strikes crown of arrogance; falling figures represent shattered ego beliefs; storm clouds purge stagnant air.",
    symbolismHi: "बिजली का गिरना अहंकार और भ्रम के टूटने का प्रतीक है, जिससे नए सत्य का निर्माण संभव हो सके।",
    icon: "⚡",
    colorGradient: "from-amber-900/40 via-red-950/40 to-slate-900/40",
    accentBorder: "border-amber-500"
  },
  "the star": {
    id: "the-star",
    name: "The Star",
    nameHi: "द स्टार (तारा / आशा, शांति व दैवीय कृपा)",
    arcana: "Major",
    suit: "Major",
    rank: "17",
    numeral: "XVII",
    element: "Air",
    elementHi: "वायु (Air)",
    astrology: "Aquarius / Hope & Healing",
    astrologyHi: "कुंभ राशि / आशा व नवजीवन",
    yesNo: "Strong Yes",
    yesNoHi: "दृढ़ हाँ (Strong Yes)",
    essence: "Hope, renewed faith, inspiration, serene healing, and cosmic blessings.",
    essenceHi: "आशा, अटूट विश्वास, प्रेरणा, शांत उपचार और ईश्वरीय आशीर्वाद।",
    keywords: ["Hope", "Faith", "Inspiration", "Healing", "Serenity"],
    keywordsHi: ["आशा", "विश्वास", "प्रेरणा", "आरोग्य", "शांति"],
    uprightMeaning: "After the storm of the Tower comes the tranquil, starlit night. Renew your faith; you are deeply blessed, inspired, and protected by the universe.",
    uprightMeaningHi: "तूफान के बाद शांत सितारों भरी रात आती है। अपनी आशा और विश्वास को फिर से जगाएं; ब्रह्मांड का आशीर्वाद आपके साथ है।",
    pastMeaning: "A beacon of hope or spiritual inspiration guided you safely through your darkest hour.",
    pastMeaningHi: "अतीत के कठिन समय में किसी उम्मीद की किरण ने आपका मार्गदर्शन किया।",
    presentMeaning: "Feel the calm rejuvenation washing over your spirit. Pursue your highest creative dreams.",
    presentMeaningHi: "मन में शांति और उत्साह का अनुभव करें। अपने सबसे ऊंचे सपनों की ओर कदम बढ़ाएं।",
    futureMeaning: "Wishes fulfilled, public acclaim, deep spiritual contentment, and brilliant prospects.",
    futureMeaningHi: "मनोकामनाओं की पूर्ति, समाज में सम्मान और एक अत्यंत सुखद व उज्ज्वल भविष्य।",
    love: "Pure, hopeful, and gentle love; healing past heartbreaks and connecting on a soul level.",
    loveHi: "पवित्र और सच्चा प्रेम, पुराने घावों का भरना और साथी के साथ आत्मिक शांति।",
    career: "Inspiring projects, creative recognition, generous opportunities, and bright future growth.",
    careerHi: "रचनात्मक कार्यों में बड़ी सफलता, नई प्रेरणा और कार्यक्षेत्र में आपकी चमक।",
    health: "Deep rejuvenation, cellular recovery, mental peace, and glowing vitality.",
    healthHi: "त्वरित स्वास्थ्य लाभ, मानसिक शांति और शरीर में नई ताजगी।",
    advice: "Keep your faith bright. Your guiding star is leading you straight home.",
    adviceHi: "विश्वास कभी न खोएं। आपकी किस्मत का सितारा आपको सही मंजिल तक ले जा रहा है।",
    symbolism: "Eight-pointed central star represents Venus / morning star; maiden pouring water onto land and stream nourishes the cosmos.",
    symbolismHi: "आठ कोनों वाला चमकीला तारा आशा का और जल प्रवाहित करती कन्या ब्रह्मांडीय पोषण का प्रतीक है।",
    icon: "⭐",
    colorGradient: "from-sky-900/30 via-indigo-900/30 to-blue-950/30",
    accentBorder: "border-sky-400"
  },
  "the moon": {
    id: "the-moon",
    name: "The Moon",
    nameHi: "द मून (चंद्रमा / भ्रम, स्वप्न व अंतर्ज्ञान)",
    arcana: "Major",
    suit: "Major",
    rank: "18",
    numeral: "XVIII",
    element: "Water",
    elementHi: "जल (Water)",
    astrology: "Pisces / Subconscious",
    astrologyHi: "मीन राशि / अवचेतन मन व स्वप्न",
    yesNo: "Caution / Unclear",
    yesNoHi: "अस्पष्ट / प्रतीक्षा करें (Unclear)",
    essence: "Navigating illusions, subconscious fears, vivid dreams, intuition, and uncovering hidden things.",
    essenceHi: "भ्रम से बचना, अवचेतन का डर, गहरे सपने, अंतर्ज्ञान और छिपी हुई बातों का खुलासा।",
    keywords: ["Illusion", "Intuition", "Subconscious", "Dreams", "Hidden Truths"],
    keywordsHi: ["भ्रम", "अंतर्ज्ञान", "अवचेतन", "रहस्य", "संदेह"],
    uprightMeaning: "Things are not what they appear under the moonlight. Avoid hasty assumptions, listen to your intuitive dreams, and navigate through murky illusions carefully.",
    uprightMeaningHi: "चांदनी रात में परछाइयां सच नहीं होतीं। किसी भी भ्रम या अफवाह से बचें और अपने अंतर्ज्ञान के सहारे आगे बढ़ें।",
    pastMeaning: "A past misunderstanding or hidden issue is still casting subtle shadows on your mindset.",
    pastMeaningHi: "अतीत का कोई भ्रम या अनसुलझा डर आज भी आपके मन में आशंका पैदा कर रहा है।",
    presentMeaning: "Do not make irreversible commitments while the waters remain murky. Seek clarity first.",
    presentMeaningHi: "जब तक स्थिति पूरी तरह साफ न हो, कोई बड़ा वादा या अनुबंध न करें।",
    futureMeaning: "The fog will lift, revealing the exact truth that was previously veiled from your sight.",
    futureMeaningHi: "जल्द ही भ्रम का पर्दा हटेगा और सच्चाई पूरी स्पष्टता के साथ सामने आ जाएगी।",
    love: "Hidden emotions, miscommunications, or romantic illusions; seek open, honest clarity.",
    loveHi: "रिश्तों में गलतफहमी या बातों को छिपाने से बचें; स्पष्ट और ईमानदार संवाद रखें।",
    career: "Beware of vague promises or hidden clauses; verify all details before signing.",
    careerHi: "दस्तावेजों को ध्यान से पढ़ें और किसी के बहकावे में आकर पेशेवर निर्णय न लें।",
    health: "Listen to mental health, anxiety management, sleep quality, and psychic sensitivities.",
    healthHi: "नींद पूरी लें, मानसिक तनाव व बेचैनी को दूर करने के लिए ध्यान का सहारा लें।",
    advice: "Trust your gut over external appearances. Wait for the light of dawn.",
    adviceHi: "दिखावे पर न जाएं, अपने अंतर्मन की सुनें और सब कुछ साफ होने का इंतजार करें।",
    symbolism: "Dog and wolf howl at the moon (tame and wild nature); crayfish emerges from the water representing primitive subconscious fears.",
    symbolismHi: "कुत्ता और भेड़िया मन के पालतू व जंगली स्वभाव को और पानी से निकलता केकड़ा गहरे अवचेतन डर को दर्शाता है।",
    icon: "🌙",
    colorGradient: "from-indigo-950/40 via-blue-950/40 to-purple-950/40",
    accentBorder: "border-indigo-400"
  },
  "the sun": {
    id: "the-sun",
    name: "The Sun",
    nameHi: "द सन (सूर्य / आनंद, सफलता व स्पष्टता)",
    arcana: "Major",
    suit: "Major",
    rank: "19",
    numeral: "XIX",
    element: "Fire",
    elementHi: "अग्नि (Fire)",
    astrology: "Sun / Vitality & Success",
    astrologyHi: "सूर्य ग्रह / तेज, यश व आरोग्य",
    yesNo: "Absolute Yes",
    yesNoHi: "पूर्ण हाँ (Absolute Yes)",
    essence: "Radiant joy, celebrated success, boundless vitality, clarity, and glorious abundance.",
    essenceHi: "प्रसन्नता, शानदार सफलता, असीम ऊर्जा, स्पष्टता और गौरवशाली समृद्धि।",
    keywords: ["Joy", "Success", "Celebration", "Vitality", "Warmth"],
    keywordsHi: ["आनंद", "सफलता", "उत्सव", "ऊर्जा", "उज्ज्वलता"],
    uprightMeaning: "The most positive card in the Tarot. The Sun illuminates your world with unbridled joy, vitality, triumph, warmth, and radiant self-confidence.",
    uprightMeaningHi: "टैरो का सबसे शुभ और सकारात्मक कार्ड। सूर्य आपके जीवन को सफलता, आरोग्य, अपार खुशियों और यश से आलोकित करता है।",
    pastMeaning: "A joyful breakthrough or loving foundation has energized your present endeavors.",
    pastMeaningHi: "अतीत की किसी बड़ी सफलता या सुखद अनुभव ने आपकी मौजूदा राह को आसान बनाया है।",
    presentMeaning: "Step into the spotlight! Everything you touch now radiates light, success, and positivity.",
    presentMeaningHi: "अपनी सफलता का आनंद लें! आपके प्रयास शुभ फल और सर्वत्र प्रशंसा लेकर आ रहे हैं।",
    futureMeaning: "Complete triumph, celebration, harmonious relationships, and glowing fulfillment.",
    futureMeaningHi: "पूर्ण विजय, मान-सम्मान में वृद्धि, खुशहाल परिवार और हर कार्य में सिद्धि।",
    love: "Radiant happiness, playful romance, marriage bliss, and genuine mutual adoration.",
    loveHi: "रिश्तों में अपार प्रेम, खुशी, विवाह और दांपत्य जीवन में मधुरता।",
    career: "Promotion, award-winning achievements, profitable ventures, and high public esteem.",
    careerHi: "पदोन्नति, व्यापार में भारी मुनाफा, पुरस्कार और कार्यक्षेत्र में शीर्ष स्थान।",
    health: "Superb vitality, vibrant energy, glowing physical wellness, and recovery.",
    healthHi: "उत्कृष्ट स्वास्थ्य, भरपूर ऊर्जा और सभी रोगों से पूर्ण मुक्ति।",
    advice: "Shine brightly and share your warmth. Success is already yours.",
    adviceHi: "पूरे आत्मविश्वास से चमकें और अपनी खुशियां बांटें। सफलता आपके साथ है।",
    symbolism: "Radiant golden sun with straight and wavy rays; innocent child riding a white horse represents pure joy and freedom.",
    symbolismHi: "उज्ज्वल सूर्य और सफेद घोड़े पर सवार बालक निश्चल आनंद, सत्य और विजय का प्रतीक है।",
    icon: "☀️",
    colorGradient: "from-amber-500/30 via-yellow-500/30 to-orange-500/30",
    accentBorder: "border-amber-300"
  },
  "judgement": {
    id: "judgement",
    name: "Judgement",
    nameHi: "जजमेंट (निर्णय / पुनर्जागरण व उच्च बुलावा)",
    arcana: "Major",
    suit: "Major",
    rank: "20",
    numeral: "XX",
    element: "Fire",
    elementHi: "अग्नि / चेतना (Fire)",
    astrology: "Pluto / Awakening",
    astrologyHi: "प्लूटो / चेतना का पुनर्जन्म",
    yesNo: "Yes",
    yesNoHi: "हाँ (Yes)",
    essence: "Spiritual awakening, answering a higher calling, forgiveness, rebirth, and decisive reckoning.",
    essenceHi: "आध्यात्मिक जागरण, आत्मा की पुकार, क्षमा, पुनरुत्थान और अंतिम निर्णय।",
    keywords: ["Awakening", "Calling", "Rebirth", "Absolution", "Clarity"],
    keywordsHi: ["पुनर्जागरण", "आत्म-पुकार", "मुक्ति", "निर्णय", "स्पष्टता"],
    uprightMeaning: "The celestial trumpet sounds for your soul's awakening. Forgive the past, heed your true inner calling, and step into your elevated life chapter with clarity.",
    uprightMeaningHi: "यह समय पुरानी गलतियों को क्षमा करने और अपने वास्तविक जीवन उद्देश्य की ओर जागने का है। एक नया अध्याय शुरू हो रहा है।",
    pastMeaning: "A pivotal choice or spiritual awakening in the past has liberated you from old guilt.",
    pastMeaningHi: "अतीत के किसी महत्वपूर्ण निर्णय ने आपको पुरानी बेड़ियों और अपराधबोध से मुक्त किया है।",
    presentMeaning: "Answer your inner calling boldly. You are ready to step onto a higher plane of life.",
    presentMeaningHi: "अपनी अंतरात्मा की आवाज पर ध्यान दें। आप अपने जीवन के उच्च स्तर पर जाने के लिए तैयार हैं।",
    futureMeaning: "Absolute clarity, karmic vindication, successful legal or personal resolutions.",
    futureMeaningHi: "समस्त संशयों का अंत, सही न्याय और आपके प्रयासों की सर्वत्र सराहना।",
    love: "Deep healing of past relationship wounds, second chances, and elevated mutual understanding.",
    loveHi: "पुरानी कड़वाहट का समाप्त होना, रिश्ते को नया जीवन मिलना और गहरा सामंजस्य।",
    career: "Finding your true vocation, stepping into visionary leadership, and receiving recognition.",
    careerHi: "अपने वास्तविक कार्यक्षेत्र की पहचान, उच्च पद और समाज में विशिष्ट स्थान।",
    health: "Complete physical and mental renewal; shedding chronic fatigue.",
    healthHi: "शारीरिक व मानसिक कायाकल्प और ऊर्जा का पुनर्संचार।",
    advice: "Listen to the call. Rise above past regrets and claim your elevated destiny.",
    adviceHi: "अतीत के पछतावे को छोड़ें और अपने उज्ज्वल भविष्य की ओर कदम बढ़ाएं।",
    symbolism: "Archangel Gabriel blows the golden trumpet; figures rise from tombs with arms outstretched toward the light.",
    symbolismHi: "देवदूत गैब्रिएल की तुरही की ध्वनि और कब्रों से उठते लोग चेतना के पुनर्जन्म और मुक्ति को दर्शाते हैं।",
    icon: "🎺",
    colorGradient: "from-purple-950/30 via-indigo-950/30 to-amber-950/30",
    accentBorder: "border-purple-400"
  },
  "the world": {
    id: "the-world",
    name: "The World",
    nameHi: "द वर्ल्ड (संसार / पूर्णता व संपूर्ण विजय)",
    arcana: "Major",
    suit: "Major",
    rank: "21",
    numeral: "XXI",
    element: "Earth",
    elementHi: "पृथ्वी / पूर्णता (Earth)",
    astrology: "Saturn / Completion",
    astrologyHi: "शनि ग्रह / चक्र की पूर्णता व सिद्धि",
    yesNo: "Strong Yes",
    yesNoHi: "पूर्ण हाँ (Strong Yes)",
    essence: "Wholeness, completion, global triumph, fulfillment of dreams, and stepping into the next cycle.",
    essenceHi: "पूर्णता, लक्ष्यों की प्राप्ति, वैश्विक सफलता, सपनों का साकार होना और सिद्धि।",
    keywords: ["Completion", "Wholeness", "Achievement", "Travel", "Fulfillment"],
    keywordsHi: ["पूर्णता", "सफलता", "उपलब्धि", "यात्रा", "सिद्धि"],
    uprightMeaning: "The grand cycle is triumphantly complete. You have achieved mastery, wholeness, and lasting success. Celebrate your victory as the entire world opens up before you.",
    uprightMeaningHi: "आपकी यात्रा सफलतापूर्वक पूरी हो चुकी है। आपने अपने लक्ष्य को प्राप्त कर लिया है। सफलता का उत्सव मनाएं, पूरा संसार आपके स्वागत के लिए तैयार है।",
    pastMeaning: "A major multi-year chapter was successfully closed, leaving you experienced and whole.",
    pastMeaningHi: "अतीत में किसी बड़े कार्य या पढ़ाई को आपने सफलतापूर्वक पूरा किया है।",
    presentMeaning: "You are at the pinnacle of achievement. Savor your victory and embrace world-expanding possibilities.",
    presentMeaningHi: "आप सफलता के शिखर पर हैं। अपनी उपलब्धियों पर गर्व करें और नए क्षितिज तलाशें।",
    futureMeaning: "Glorious culmination of all your hard work, international travel, and total harmony.",
    futureMeaningHi: "समस्त परिश्रम का श्रेष्ठ फल, विदेश यात्रा और जीवन में संपूर्ण संतुष्टि।",
    love: "Fulfilling lifelong partnership, marriage, travel together, and mutual wholeness.",
    loveHi: "प्रेम में पूर्णता, विवाह, साथ में यात्राएं और एक संपूर्ण खुशहाल जीवन।",
    career: "Reaching the summit of career ambitions, international acclaim, and finishing landmark projects.",
    careerHi: "कैरियर के सर्वोच्च शिखर पर पहुंचना, अंतरराष्ट्रीय ख्याति और बड़ी परियोजनाओं की पूर्णता।",
    health: "Total vitality, mind-body-spirit equilibrium, and optimum physical wellbeing.",
    healthHi: "तन, मन और आत्मा का संपूर्ण संतुलन और उत्तम आरोग्य।",
    advice: "Celebrate your completion. The world is in your hands.",
    adviceHi: "अपनी विजय का उत्सव मनाएं। पूरी दुनिया आपकी सफलता की साक्षी है।",
    symbolism: "Green laurel wreath of victory; four figures in corners represent mastery of all four elements and seasons.",
    symbolismHi: "विजय की हरी माला और चारों कोनों में मौजूद प्राणी चारों तत्वों और ब्रह्मांड पर पूर्ण नियंत्रण के प्रतीक हैं।",
    icon: "🌍",
    colorGradient: "from-emerald-900/30 via-indigo-900/30 to-amber-900/30",
    accentBorder: "border-emerald-400"
  }
};

// Helper generator for Minor Arcana cards to cover all 56 cards comprehensively!
const MINOR_SUITS_CONFIG: Record<string, {
  suitHi: string;
  element: 'Water' | 'Fire' | 'Air' | 'Earth';
  elementHi: string;
  theme: string;
  themeHi: string;
  icon: string;
  gradient: string;
  border: string;
}> = {
  "Cups": {
    suitHi: "प्याले (Cups)",
    element: "Water",
    elementHi: "जल तत्व (Water)",
    theme: "Love, emotions, intuition, relationships, and spiritual healing.",
    themeHi: "प्रेम, भावनाएं, अंतर्ज्ञान, संबंध और आत्मिक शांति।",
    icon: "🏆",
    gradient: "from-blue-900/30 via-cyan-900/30 to-indigo-950/30",
    border: "border-cyan-400"
  },
  "Wands": {
    suitHi: "छड़ी / दंड (Wands)",
    element: "Fire",
    elementHi: "अग्नि तत्व (Fire)",
    theme: "Passion, creative energy, inspiration, ambition, and swift action.",
    themeHi: "उत्साह, रचनात्मक ऊर्जा, प्रेरणा, महत्वाकांक्षा और त्वरित कार्रवाई।",
    icon: "🥢",
    gradient: "from-amber-900/30 via-orange-900/30 to-red-950/30",
    border: "border-amber-400"
  },
  "Swords": {
    suitHi: "तलवारें (Swords)",
    element: "Air",
    elementHi: "वायु तत्व (Air)",
    theme: "Intellect, decision-making, mental clarity, communication, and overcoming conflict.",
    themeHi: "बुद्धि, निर्णय क्षमता, मानसिक स्पष्टता, संवाद और चुनौतियों का सामना।",
    icon: "⚔️",
    gradient: "from-slate-800/30 via-indigo-900/30 to-sky-950/30",
    border: "border-sky-400"
  },
  "Pentacles": {
    suitHi: "सिक्के (Pentacles)",
    element: "Earth",
    elementHi: "पृथ्वी तत्व (Earth)",
    theme: "Wealth, material success, career, health, physical foundation, and long-term security.",
    themeHi: "धन-संपत्ति, व्यावसायिक सफलता, स्वास्थ्य, भौतिक सुरक्षा और स्थायित्व।",
    icon: "🪙",
    gradient: "from-emerald-950/30 via-amber-950/30 to-stone-900/30",
    border: "border-emerald-400"
  }
};

// Detailed definitions for all Minor Arcana Ranks per suit
const MINOR_RANKS_DETAILS: Record<string, {
  rankHi: string;
  astrology: string;
  astrologyHi: string;
  yesNo: string;
  yesNoHi: string;
  essenceSuffix: string;
  essenceSuffixHi: string;
  keywords: string[];
  keywordsHi: string[];
  uprightDesc: string;
  uprightDescHi: string;
  past: string;
  pastHi: string;
  present: string;
  presentHi: string;
  future: string;
  futureHi: string;
  love: string;
  loveHi: string;
  career: string;
  careerHi: string;
  health: string;
  healthHi: string;
  advice: string;
  adviceHi: string;
  symbolism: string;
  symbolismHi: string;
}> = {
  "Ace": {
    rankHi: "इक्का (Ace)",
    astrology: "Root of the Element",
    astrologyHi: "तत्व का मूल स्रोत",
    yesNo: "Strong Yes",
    yesNoHi: "दृढ़ हाँ (Strong Yes)",
    essenceSuffix: "a pure spark of potential, fresh opportunity, and pristine beginnings.",
    essenceSuffixHi: "संभावनाओं का शुद्ध बीज, नया अवसर और शुभ शुरुआत।",
    keywords: ["Fresh Opportunity", "Pure Potential", "Inspiration", "New Seed", "Breakthrough"],
    keywordsHi: ["नया अवसर", "संभावना", "प्रेरणा", "शुभ आरंभ", "सफलता"],
    uprightDesc: "The Ace brings an auspicious burst of pure elemental energy. A golden gateway of opportunity has opened. Take the seed and plant it with confidence.",
    uprightDescHi: "इक्का नई ऊर्जा और सुनहरे अवसरों का द्वार खोलता है। इस अवसर को पूरे आत्मविश्वास के साथ अपनाएं।",
    past: "A fresh seed planted in the past is now ready to expand and bear fruit.",
    pastHi: "अतीत में शुरू किया गया नया काम अब फल देने के लिए तैयार है।",
    present: "You are being gifted a brand-new beginning. Seize this golden opening immediately.",
    presentHi: "आपको एक नई और शानदार शुरुआत का अवसर मिल रहा है। इसे तुरंत स्वीकारें।",
    future: "A magnificent new venture, relationship, or breakthrough will present itself.",
    futureHi: "भविष्य में एक नई प्रेरणादायक परियोजना या संबंध आपके सामने आएगा।",
    love: "New romance, heartfelt confession, or a revitalized emotional spark.",
    loveHi: "नया प्रेम संबंध, दिल की बात कहना या रिश्ते में नई ताजगी।",
    career: "New job offer, creative venture, investment opportunity, or winning contract.",
    careerHi: "नई नौकरी का प्रस्ताव, नया व्यवसाय या लाभप्रद निवेश।",
    health: "Surge of vitality, starting a healthy routine, and natural healing.",
    healthHi: "नई ऊर्जा, स्वस्थ दिनचर्या की शुरुआत और प्राकृतिक आरोग्यता।",
    advice: "Take this fresh seed and nurture it boldly. The potential is unlimited.",
    adviceHi: "इस नए अवसर को पूरे समर्पण से संवारें। संभावनाएं असीम हैं।",
    symbolism: "Divine hand emerging from clouds offering the elemental gift; lush landscape below signifies fertile potential.",
    symbolismHi: "बादलों से निकलता दैवीय हाथ उपहार स्वरूप तत्व भेंट करता है, जो नए आरंभ का प्रतीक है।"
  },
  "2": {
    rankHi: "दुक्की (Two)",
    astrology: "Moon / Balance & Partnership",
    astrologyHi: "संतुलन व साझेदारी",
    yesNo: "Yes",
    yesNoHi: "हाँ (Yes)",
    essenceSuffix: "duality, partnership, balanced planning, and mutual cooperation.",
    essenceSuffixHi: "द्वंद्व, साझेदारी, संतुलित योजना और परस्पर सहयोग।",
    keywords: ["Partnership", "Balance", "Planning", "Duality", "Connection"],
    keywordsHi: ["साझेदारी", "संतुलन", "योजना", "तालमेल", "सद्भाव"],
    uprightDesc: "Two represents harmony between two forces, forging partnerships, and planning the next steps with balance.",
    uprightDescHi: "दो नंबर संतुलन, साझेदारी और दो विपरीत ताकतों के बीच सामंजस्य का प्रतीक है।",
    past: "Past collaboration or dual choices formed the foundation of your situation.",
    pastHi: "अतीत की किसी साझेदारी या निर्णय ने वर्तमान स्थिति को आकार दिया है।",
    present: "Find equilibrium. Join forces with trusted allies or weigh your two paths carefully.",
    presentHi: "संतुलन बनाएं। भरोसेमंद सहयोगियों के साथ मिलकर आगे बढ़ें।",
    future: "Fruitful partnership, mutual understanding, and steady progress.",
    futureHi: "सफल साझेदारी और परस्पर समझदारी से निरंतर प्रगति होगी।",
    love: "Mutual attraction, soulmate harmony, and balanced give-and-take.",
    loveHi: "आपसी आकर्षण, रिश्ते में बराबरी और गहरा भावनात्मक तालमेल।",
    career: "Successful contracts, smooth negotiations, and co-founding ventures.",
    careerHi: "सफल अनुबंध, व्यापारिक समझौते और साझीदार के साथ लाभ।",
    health: "Balancing diet, sleep, and emotional equilibrium.",
    healthHi: "आहार, नींद और व्यायाम में संतुलन बनाकर रखें।",
    advice: "Collaborate and keep your balance. Two minds are better than one.",
    adviceHi: "मिलकर काम करें और जीवन में संतुलन बनाए रखें।",
    symbolism: "Two mirrored symbols representing reciprocity, harmony, and mutual respect.",
    symbolismHi: "दो समान प्रतीक संतुलन, सम्मान और परस्पर सहयोग को दर्शाते हैं।"
  },
  "3": {
    rankHi: "तिक्की (Three)",
    astrology: "Jupiter / Growth & Celebration",
    astrologyHi: "बृहस्पति / वृद्धि व उत्सव",
    yesNo: "Strong Yes",
    yesNoHi: "दृढ़ हाँ (Strong Yes)",
    essenceSuffix: "creative expansion, teamwork, joyful celebration, and visible progress.",
    essenceSuffixHi: "रचनात्मक विस्तार, टीमवर्क, उत्सव और स्पष्ट प्रगति।",
    keywords: ["Celebration", "Expansion", "Teamwork", "Growth", "Community"],
    keywordsHi: ["उत्सव", "विस्तार", "टीमवर्क", "वृद्धि", "सफलता"],
    uprightDesc: "Three brings initial success, communal celebration, creative collaboration, and stepping into joyful expansion.",
    uprightDescHi: "तीन नंबर शुरुआती सफलता, सामूहिक उत्सव और रचनात्मक सहयोग लेकर आता है।",
    past: "Hard work in a group or early seeds have now blossomed into measurable momentum.",
    pastHi: "अतीत में किए गए सामूहिक प्रयास अब सफल परिणाम दे रहे हैं।",
    present: "Celebrate your milestones with friends and community. Build together.",
    presentHi: "अपनी सफलताओं का अपनों के साथ उत्सव मनाएं और मिलकर आगे बढ़ें।",
    future: "Greater expansion, recognition, fruitful creative projects, and shared joy.",
    futureHi: "व्यापक विस्तार, सम्मान और साझा खुशियों का समय आएगा।",
    love: "Joyous gatherings, engagement parties, deepening social bonds, and lighthearted fun.",
    loveHi: "खुशनुमा पल, सामाजिक समारोह और रिश्ते में आनंद व मिठास।",
    career: "Collaborative triumph, client appreciation, craftsmanship praise, and expanding reach.",
    careerHi: "टीम की सफलता, ग्राहकों की सराहना और कार्यक्षेत्र में विस्तार।",
    health: "High spirits, vitality through social connection and creative hobbies.",
    healthHi: "प्रसन्न मन, सामाजिक सहयोग और रचनात्मक गतिविधियों से स्वास्थ्य लाभ।",
    advice: "Celebrate how far you've come and welcome collaborative support.",
    adviceHi: "अपनी प्रगति की सराहना करें और सहयोग का स्वागत करें।",
    symbolism: "Three figures or elements united in harmony and triumph.",
    symbolismHi: "तीन तत्वों या व्यक्तियों का मिलन एकता और सफलता का सूचक है।"
  },
  "4": {
    rankHi: "चौकी (Four)",
    astrology: "Sun / Stability & Security",
    astrologyHi: "सूर्य / स्थिरता व सुरक्षा",
    yesNo: "Yes",
    yesNoHi: "हाँ (Yes)",
    essenceSuffix: "stability, solid foundations, resting, and home security.",
    essenceSuffixHi: "स्थिरता, मजबूत नींव, विश्राम और पारिवारिक सुरक्षा।",
    keywords: ["Stability", "Foundation", "Security", "Rest", "Structure"],
    keywordsHi: ["स्थिरता", "मजबूत नींव", "सुरक्षा", "विश्राम", "संरचना"],
    uprightDesc: "Four represents setting firm roots, enjoying domestic peace, or establishing structural security.",
    uprightDescHi: "चार नंबर मजबूत नींव, घरेलू शांति और जीवन में सुरक्षा व स्थिरता को दर्शाता है।",
    past: "You established solid groundwork that protects you today.",
    pastHi: "अतीत में बनाई गई मजबूत नींव आज आपको सुरक्षा प्रदान कर रही है।",
    present: "Enjoy your stable sanctuary. Do not rush unnecessarily; consolidate your gains.",
    presentHi: "वर्तमान स्थिरता का आनंद लें। जल्दबाजी से बचें और अपनी स्थिति मजबूत करें।",
    future: "Long-term home security, celebration of milestones, and peaceful stability.",
    futureHi: "घर में शांति, दीर्घकालिक सुरक्षा और सुखद स्थायित्व।",
    love: "Home harmony, wedding, moving in together, and feeling deeply safe.",
    loveHi: "पारिवारिक सुख, विवाह, साथ में घर बसाना और सुरक्षा का अहसास।",
    career: "Secure employment, solid real estate, sustainable business models.",
    careerHi: "सुरक्षित नौकरी, स्थायी व्यापारिक ढांचा और वित्तीय स्थिरता।",
    health: "Good recovery, restorative rest, grounding exercises.",
    healthHi: "पर्याप्त विश्राम और संतुलित दिनचर्या से आरोग्य।",
    advice: "Appreciate your foundation. Build upon what is already proven and solid.",
    adviceHi: "अपनी मजबूत नींव का सम्मान करें और उसी पर आगे का निर्माण करें।",
    symbolism: "Four pillars or bower forming a protective, grounded perimeter.",
    symbolismHi: "चार खंभे या सीमाएं सुरक्षा और स्थायित्व का प्रतीक हैं।"
  },
  "5": {
    rankHi: "पंजी (Five)",
    astrology: "Mercury / Change & Challenge",
    astrologyHi: "बुध / चुनौती व परिवर्तन",
    yesNo: "Caution / Adapt",
    yesNoHi: "सावधानी / अनुकूलन (Caution)",
    essenceSuffix: "temporary conflict, adaptation, learning from friction, and rising above turbulence.",
    essenceSuffixHi: "अस्थायी चुनौती, मतभेद, घर्षण से सीखना और संघर्ष से उबरना।",
    keywords: ["Conflict", "Adaptation", "Change", "Learning", "Resilience"],
    keywordsHi: ["चुनौती", "परिवर्तन", "सीख", "मतभेद", "धैर्य"],
    uprightDesc: "Five represents a stormy test of character. View friction not as defeat, but as a catalyst to grow stronger and smarter.",
    uprightDescHi: "पांच नंबर जीवन की परीक्षा और मतभेद का सूचक है। इसे असफलता न समझें, बल्कि इससे सीखकर और मजबूत बनें।",
    past: "A past trial tested your endurance and taught you valuable wisdom.",
    pastHi: "अतीत की किसी कठिन परिस्थिति ने आपको परिपक्व बनाया है।",
    present: "Pick your battles wisely. Do not let petty arguments drain your vital energy.",
    presentHi: "व्यर्थ के वाद-विवाद से बचें और अपनी ऊर्जा सही दिशा में लगाएं।",
    future: "Turbulence will subside, leaving you more resilient and clear-minded.",
    futureHi: "मुश्किल समय जल्द बीतेगा और आप अधिक मजबूत बनकर उभरेंगे।",
    love: "Communication tension or ego clashes; practice active listening and empathy.",
    loveHi: "गलतफहमी या अहंकार के टकराव से बचें; धैर्यपूर्वक बातचीत करें।",
    career: "Workplace competition, renegotiating terms, managing tricky deadlines.",
    careerHi: "कार्यक्षेत्र में प्रतिस्पर्धा; चतुराई और शांति से काम लें।",
    health: "Manage stress, release pent-up frustration, gentle stretching.",
    healthHi: "तनाव से बचें और मानसिक शांति के लिए योग करें।",
    advice: "Rise above the drama. True strength adapts and overcomes gracefully.",
    adviceHi: "छोटी बातों से ऊपर उठें। समझदारी और धैर्य से हर चुनौती को पार करें।",
    symbolism: "Dispersed or conflicting symbols that require conscious alignment.",
    symbolismHi: "अलग-अलग दिशाओं में जाती ऊर्जाएं जिन्हें केंद्रित करने की आवश्यकता है।"
  },
  "6": {
    rankHi: "छक्की (Six)",
    astrology: "Venus / Harmony & Moving Forward",
    astrologyHi: "शुक्र / सद्भाव व सुगम यात्रा",
    yesNo: "Yes",
    yesNoHi: "हाँ (Yes)",
    essenceSuffix: "restoration, moving to calmer waters, generosity, and sweet nostalgia.",
    essenceSuffixHi: "पुनर्स्थापना, शांत जल की ओर यात्रा, उदारता और सुखद स्मृतियां।",
    keywords: ["Harmony", "Transition", "Generosity", "Peace", "Healing"],
    keywordsHi: ["सद्भाव", "शांति", "उदारता", "सुलह", "शुभ यात्रा"],
    uprightDesc: "Six restores harmony after the storm of the Five. You are moving toward calmer waters, receiving support, or savoring sweet memories.",
    uprightDescHi: "छह नंबर संघर्ष के बाद शांति और सुखद बदलाव लाता है। आप कठिन परिस्थितियों से निकलकर शांत वातावरण की ओर बढ़ रहे हैं।",
    past: "Past good deeds or lessons have earned you current peace and safe passage.",
    pastHi: "अतीत के आपके अच्छे कर्म आज आपको राहत और सुरक्षा दे रहे हैं।",
    present: "Accept help generously offered. Leave turbulent drama behind.",
    presentHi: "दूसरों की सहायता स्वीकार करें और तनावपूर्ण माहौल से दूरी बनाएं।",
    future: "Smooth sailing ahead, successful relocation, or warm reunion.",
    futureHi: "आगे का रास्ता सुगम होगा; यात्राएं सफल होंगी और शांति मिलेगी।",
    love: "Nostalgic sweetness, reconciliation, mutual sharing, and gentle romance.",
    loveHi: "रिश्ते में मिठास, पुरानी बातें भूलकर नई शुरुआत और आपसी प्रेम।",
    career: "Financial assistance, smooth job transitions, winning collaborative projects.",
    careerHi: "वित्तीय मदद, कार्यक्षेत्र में अनुकूल बदलाव और पदोन्नति।",
    health: "Convalescence, mental relief, healing therapy.",
    healthHi: "रोगों से राहत, मानसिक शांति और त्वरित सुधार।",
    advice: "Let yourself be guided to calmer shores. Accept kindness with an open heart.",
    adviceHi: "शांति की ओर बढ़ें और दूसरों के स्नेह व सहयोग का सम्मान करें।",
    symbolism: "Ferry moving toward calm waters or cups filled with flowers.",
    symbolismHi: "नाव का शांत किनारों की ओर बढ़ना और फूलों से भरे पात्र शांति के प्रतीक हैं।"
  },
  "7": {
    rankHi: "सत्ती (Seven)",
    astrology: "Moon / Reflection & Strategic Choice",
    astrologyHi: "चंद्रमा / आत्ममंथन व रणनीति",
    yesNo: "Maybe / Assess",
    yesNoHi: "विचार करें (Assess)",
    essenceSuffix: "strategic choices, perseverance, evaluating options, and avoiding self-deception.",
    essenceSuffixHi: "रणनीतिक चुनाव, धैर्य, विकल्पों का मूल्यांकन और भ्रम से बचना।",
    keywords: ["Strategy", "Patience", "Evaluation", "Choices", "Perseverance"],
    keywordsHi: ["रणनीति", "धैर्य", "मूल्यांकन", "विकल्प", "सावधानी"],
    uprightDesc: "Seven calls for intelligent assessment. Look past illusions, protect your gains with smart tactics, and evaluate your long-term return on investment.",
    uprightDescHi: "सात नंबर सही रणनीति और धैर्य की मांग करता है। भ्रम से बचें और अपने दीर्घकालिक लाभ के लिए सोच-समझकर निर्णय लें।",
    past: "Past investments or careful planning are reaching a critical evaluation stage.",
    pastHi: "अतीत में लगाई गई पूंजी या मेहनत अब मूल्यांकन के चरण में है।",
    present: "Weigh your choices carefully. Cut through wishful thinking with practical strategy.",
    presentHi: "हवा-हवाई बातों से बचें और ठोस तथ्यों के आधार पर रणनीति बनाएं।",
    future: "Patience will reward your persistent discipline with tangible harvests.",
    futureHi: "आपका धैर्य और सही योजना भविष्य में उत्तम परिणाम लाएगी।",
    love: "Clarifying expectations, avoiding wishful projections, choosing authentic love.",
    loveHi: "रिश्ते में स्पष्टता रखें और केवल कल्पनाओं में जीने से बचें।",
    career: "Strategic repositioning, auditing investments, standing your ground with finesse.",
    careerHi: "व्यापारिक रणनीति का पुनरीक्षण और चतुराई से अपने हितों की रक्षा करना।",
    health: "Patience with recovery, maintaining consistent wellness routines.",
    healthHi: "धैर्य रखें; निरंतर व्यायाम और सही आहार से धीरे-धीरे लाभ होगा।",
    advice: "Look before you leap. Choose the option grounded in reality, not fantasy.",
    adviceHi: "सोच-समझकर कदम बढ़ाएं। कल्पना के बजाय यथार्थ को चुनें।",
    symbolism: "Multiple choices or defending a high vantage point.",
    symbolismHi: "कई विकल्प या ऊंचे स्थान से अपने हितों की रक्षा का दृश्य।"
  },
  "8": {
    rankHi: "अट्ठी (Eight)",
    astrology: "Saturn / Mastery & Swift Movement",
    astrologyHi: "शनि / कुशलता व तेज गति",
    yesNo: "Yes",
    yesNoHi: "हाँ (Yes)",
    essenceSuffix: "skill mastery, dedicated craftsmanship, swift progress, or moving on to higher purpose.",
    essenceSuffixHi: "कौशल में निपुणता, समर्पण, तीव्र प्रगति और उच्च उद्देश्य की ओर प्रस्थान।",
    keywords: ["Mastery", "Craftsmanship", "Speed", "Diligence", "Transition"],
    keywordsHi: ["निपुणता", "परिश्रम", "तीव्रता", "समर्पण", "प्रगति"],
    uprightDesc: "Eight is the mark of dedicated mastery and rapid momentum. Whether honing your craft or walking away from unfulfilling situations, you are advancing rapidly.",
    uprightDescHi: "आठ नंबर कठोर परिश्रम, कला में निपुणता और तेज गति से आगे बढ़ने का प्रतीक है।",
    past: "Consistent dedication and hard practice built your current expertise.",
    pastHi: "अतीत के निरंतर अभ्यास ने आपको इस क्षेत्र में कुशल बनाया है।",
    present: "Focus on excellence and polish your skills. Messages and progress arrive swiftly.",
    presentHi: "अपने काम में उत्कृष्टता लाएं। कार्य तेजी से आगे बढ़ेंगे।",
    future: "High mastery, international acclaim, rapid advancement, and profound self-respect.",
    futureHi: "उच्च पद, कार्य में महारत और समाज में मान-सम्मान।",
    love: "Swift romance, direct honest messages, or walking away from dead-end relationships.",
    loveHi: "स्पष्ट बातचीत, प्रेम में तेजी या व्यर्थ के रिश्तों को अलविदा कहना।",
    career: "Learning advanced skills, rapid promotions, high production volume, career mastery.",
    careerHi: "नई तकनीक सीखना, पदोन्नति और कार्यक्षेत्र में आपकी विशेषज्ञता की धाक।",
    health: "High endurance, regular disciplined fitness, positive momentum.",
    healthHi: "मजबूत शारीरिक सहनशक्ति और नियमित व्यायाम का लाभ।",
    advice: "Dedicate yourself fully to your craft. Excellence is never an accident.",
    adviceHi: "अपने काम में पूरा मन लगाएं। निरंतर अभ्यास ही सफलता की कुंजी है।",
    symbolism: "Artisan engraving coins or flying arrows cutting through the clear sky.",
    symbolismHi: "सिक्कों पर नक्काशी करता शिल्पी या खुले आकाश में उड़ते तीर।"
  },
  "9": {
    rankHi: "नहले (Nine)",
    astrology: "Mars / Fulfillment & Near Completion",
    astrologyHi: "मंगल / पूर्णता के निकट व आत्म-संतुष्टि",
    yesNo: "Strong Yes",
    yesNoHi: "दृढ़ हाँ (Strong Yes)",
    essenceSuffix: "near-culmination, wish fulfillment, self-reliance, and resilience in the home stretch.",
    essenceSuffixHi: "लक्ष्य के बिल्कुल करीब, मनोकामना पूर्ति, आत्मनिर्भरता और अंतिम चरण में धैर्य।",
    keywords: ["Fulfillment", "Resilience", "Wishes Granted", "Self-Reliance", "Victory"],
    keywordsHi: ["मनोकामना पूर्ति", "संतुष्टि", "धैर्य", "आत्मनिर्भरता", "सफलता"],
    uprightDesc: "Nine represents reaching the threshold of your dreams. Stand resilient for the final stretch or savor the sweet wine of personal satisfaction.",
    uprightDescHi: "नौ नंबर मनोकामनाओं के पूर्ण होने और लक्ष्य के अंतिम छोर पर पहुंचने का संकेत देता है।",
    past: "Your enduring courage through past challenges brought you to this threshold of victory.",
    pastHi: "अतीत के आपके साहस और धीरज ने आपको इस मुकाम तक पहुंचाया है।",
    present: "Do not give up now—you are inches from the finish line. Savor your self-sufficiency.",
    presentHi: "अंतिम समय में हिम्मत न हारें; सफलता बस कुछ ही कदम दूर है।",
    future: "Wishes granted, luxurious contentment, material security, and well-earned peace.",
    futureHi: "सपनों का साकार होना, सुख-सुविधाएं और आत्मिक शांति।",
    love: "Deep personal happiness, feeling complete within yourself, or romantic wish fulfillment.",
    loveHi: "मनपसंद जीवनसाथी, प्रेम में पूर्ण संतुष्टि और सुखद वैवाहिक जीवन।",
    career: "Reaching high financial independence, solo success, completing major milestones.",
    careerHi: "वित्तीय आत्मनिर्भरता, व्यापार में बड़ा मुकाम और लक्ष्यों की प्राप्ति।",
    health: "Robust vitality, recovering stamina, holistic wellness.",
    healthHi: "उत्तम स्वास्थ्य और मानसिक व शारीरिक मजबूती।",
    advice: "Stand tall. You have nearly conquered the mountain.",
    adviceHi: "अडिग रहें। आप अपनी मंजिल के बिल्कुल करीब हैं।",
    symbolism: "Figure resting proudly with nine full vessels or standing guard near nine staves.",
    symbolismHi: "नौ पात्रों के सामने संतुष्ट बैठा व्यक्ति या नौ लाठियों के सहारे खड़ा रक्षक।"
  },
  "10": {
    rankHi: "दहले (Ten)",
    astrology: "Pluto / Culmination & Cycle End",
    astrologyHi: "प्लूटो / चक्र की पूर्णता व नया सवेरा",
    yesNo: "Strong Yes",
    yesNoHi: "दृढ़ हाँ (Strong Yes)",
    essenceSuffix: "ultimate culmination, lasting legacy, family abundance, or closing an exhausting burden.",
    essenceSuffixHi: "चक्र की पूर्णता, स्थायी विरासत, पारिवारिक सुख और भारी बोझ से मुक्ति।",
    keywords: ["Legacy", "Culmination", "Abundance", "Completion", "Renewal"],
    keywordsHi: ["विरासत", "पूर्णता", "समृद्धि", "समापन", "नया अध्याय"],
    uprightDesc: "Ten brings the full circle of the suit. Generational wealth, emotional bliss, or shedding an exhausted load to start afresh.",
    uprightDescHi: "दस नंबर किसी भी यात्रा की पूर्णता, पारिवारिक समृद्धि और पुराने बोझ के उतरने का प्रतीक है।",
    past: "A massive life cycle or family legacy laid the foundation for your current world.",
    pastHi: "अतीत के पारिवारिक संस्कारों या पुराने प्रयासों ने आज यह मुकाम दिया है।",
    present: "Celebrate absolute abundance and release whatever burdens have run their course.",
    presentHi: "उपलब्धियों का आनंद लें और जो बोझ अब जरूरी नहीं है उसे उतार दें।",
    future: "Generational prosperity, lasting family happiness, and complete fulfillment.",
    futureHi: "दीर्घकालिक समृद्धि, पारिवारिक खुशियां और संपूर्ण संतुष्टि।",
    love: "Happy family life, lifelong marriage commitment, home blessings, and shared joy.",
    loveHi: "खुशहाल गृहस्थी, अटूट वैवाहिक बंधन और संतानों का सुख।",
    career: "Pinnacle of organizational success, passing on a rich business legacy, wealth security.",
    careerHi: "व्यापार में ऐतिहासिक सफलता, स्थायी संपत्ति और उच्च प्रतिष्ठा।",
    health: "Total recovery, releasing burnout, restoring bodily harmony.",
    healthHi: "थकान से मुक्ति, पूर्ण स्वास्थ्य लाभ और ऊर्जा का संचार।",
    advice: "Honor your accomplishments and step joyfully into the next higher cycle.",
    adviceHi: "अपनी सफलताओं को संजोएं और नए उत्साह से आगे बढ़ें।",
    symbolism: "Rainbow of ten cups, family gathered under archway, or setting down a heavy bundle of ten wands.",
    symbolismHi: "आकाश में दस प्यालों का इंद्रधनुष या भव्य प्रवेश द्वार के नीचे खुशहाल परिवार।"
  },
  "Page": {
    rankHi: "गुलाम / दूत (Page)",
    astrology: "Earth of the Suit / Youthful Messenger",
    astrologyHi: "उत्साही दूत व नई शुरुआत",
    yesNo: "Yes",
    yesNoHi: "हाँ (Yes)",
    essenceSuffix: "curious news, youthful enthusiasm, fresh ideas, and learning with an open heart.",
    essenceSuffixHi: "शुभ समाचार, युवा उत्साह, नए विचार और खुले दिल से सीखना।",
    keywords: ["Message", "Curiosity", "Youthful Energy", "New Idea", "Student"],
    keywordsHi: ["संदेश", "जिज्ञासा", "उत्साह", "नया विचार", "सीखना"],
    uprightDesc: "The Page arrives as an eager messenger carrying exciting news, creative inspiration, or study opportunities. Approach life with child-like curiosity.",
    uprightDescHi: "पेज एक उत्साही दूत की तरह शुभ समाचार, नई प्रेरणा और सीखने के अवसर लेकर आता है।",
    past: "An early spark of interest or message set this current adventure in motion.",
    pastHi: "अतीत में मिली किसी सूचना या रुचि ने इस यात्रा की शुरुआत की थी।",
    present: "Keep an open mind and absorb new knowledge. Expect pleasant messages.",
    presentHi: "जिज्ञासु बने रहें और नई चीजें सीखें। शुभ समाचार मिलने वाले हैं।",
    future: "Exciting invitations, educational success, and stepping onto an inspiring path.",
    futureHi: "उत्साहजनक प्रस्ताव, शिक्षा में सफलता और नए मार्ग का खुलना।",
    love: "Flirtatious messages, youthful romance, heartfelt love letters, or new crushes.",
    loveHi: "प्रेम संदेश, रिश्ते में मासूमियत और नए आकर्षण की शुरुआत।",
    career: "Internships, exciting junior projects, learning high-demand skills, entry-level wins.",
    careerHi: "नई नौकरी या इंटर्नशिप, नए प्रोजेक्ट और कौशल सीखने के अवसर।",
    health: "Youthful vitality, starting a new sport, playful physical activities.",
    healthHi: "खेलकूद, नई व्यायाम शैली और ताजगी भरी ऊर्जा।",
    advice: "Stay curious and humble. Every master was once a beginner.",
    adviceHi: "जिज्ञासु और विनम्र बने रहें। सीखने की ललक बनाए रखें।",
    symbolism: "Youthful figure dressed in tunic intently inspecting the suit's emblem.",
    symbolismHi: "उत्साही युवक अपने हाथ में मौजूद प्रतीक का ध्यानपूर्वक अध्ययन करता हुआ।"
  },
  "Knight": {
    rankHi: "सवार / योद्धा (Knight)",
    astrology: "Fire of the Suit / Driven Action",
    astrologyHi: "गति, साहस व अभियान",
    yesNo: "Strong Yes (Fast Action)",
    yesNoHi: "दृढ़ हाँ (शीघ्र कार्रवाई)",
    essenceSuffix: "dynamic drive, pursuit of ideals, chivalry, swift movement, and dedicated quest.",
    essenceSuffixHi: "ऊर्जावान संकल्प, लक्ष्यों का पीछा, साहसी कदम और त्वरित प्रगति।",
    keywords: ["Action", "Drive", "Quest", "Adventure", "Courage"],
    keywordsHi: ["कार्रवाई", "साहस", "अभियान", "गति", "वीरता"],
    uprightDesc: "The Knight gallops into action on his trusty steed. Charge forward with passion and focused energy, but remain mindful of your direction.",
    uprightDescHi: "नाइट अदम्य साहस और गति के साथ आगे बढ़ने का प्रतीक है। अपने लक्ष्य की ओर पूरे वेग से बढ़ें।",
    past: "A bold, decisive leap or intense effort gained you valuable ground.",
    pastHi: "अतीत में उठाए गए किसी साहसी कदम ने आपको बढ़त दिलाई है।",
    present: "Take bold action without delay. Channel your intense passion productively.",
    presentHi: "बिना समय गंवाए सक्रिय कदम उठाएं। अपनी ऊर्जा को सही दिशा दें।",
    future: "Swift victory, overcoming long distances, exciting career travels.",
    futureHi: "तेजी से सफलता, यात्राएं और लक्ष्यों की शीघ्र प्राप्ति।",
    love: "Charming suitor, passionate whirlwind romance, bold romantic pursuit.",
    loveHi: "उत्साही प्रेमी, तीव्र प्रेम संबंध और रिश्ते में रोमांच।",
    career: "Aggressive business expansion, crushing sales targets, tackling demanding challenges.",
    careerHi: "व्यापार में तेजी से विस्तार, लक्ष्यों की प्राप्ति और नए बाजारों में प्रवेश।",
    health: "High endurance, athletic energy, dynamic sports.",
    healthHi: "मजबूत स्टैमिना और गतिशील व्यायाम से स्वास्थ्य लाभ।",
    advice: "Ride boldly toward your dream. Do not let hesitation slow your gallop.",
    adviceHi: "साहस के साथ आगे बढ़ें। संकोच को अपनी गति न रोकने दें।",
    symbolism: "Knight mounted on a charging horse ready for the noble quest.",
    symbolismHi: "घोड़े पर सवार शूरवीर अपने लक्ष्य की ओर तेजी से बढ़ता हुआ।"
  },
  "Queen": {
    rankHi: "रानी (Queen)",
    astrology: "Water of the Suit / Emotional Mastery",
    astrologyHi: "आंतरिक ज्ञान, पोषण व गरिमा",
    yesNo: "Strong Yes",
    yesNoHi: "दृढ़ हाँ (Strong Yes)",
    essenceSuffix: "nurturing leadership, emotional intelligence, abundance, intuition, and graceful sovereignty.",
    essenceSuffixHi: "पोषणकारी नेतृत्व, भावनात्मक परिपक्वता, समृद्धि, अंतर्ज्ञान और गरिमा।",
    keywords: ["Nurturing", "Intuition", "Grace", "Abundance", "Confidence"],
    keywordsHi: ["पोषण", "अंतर्ज्ञान", "गरिमा", "समृद्धि", "आत्मविश्वास"],
    uprightDesc: "The Queen embodies mature, magnetic authority tempered with empathy and creative grace. Trust your instincts and lead with heart.",
    uprightDescHi: "क्वीन आंतरिक शक्ति, संवेदनशीलता, करुणा और गरिमापूर्ण नेतृत्व का प्रतीक है।",
    past: "A compassionate mentor or your own emotional maturity supported your growth.",
    pastHi: "किसी समझदार मार्गदर्शक या आपकी आंतरिक परिपक्वता ने आपको संवारा है।",
    present: "Rule your domain with love, self-assurance, and welcoming warmth.",
    presentHi: "अपने कार्य और परिवार को प्यार, आत्मविश्वास और गरिमा से संभालें।",
    future: "Respected stature, thriving home/work environment, and deep emotional contentment.",
    futureHi: "उच्च सम्मान, समृद्ध वातावरण और आत्मिक शांति की प्राप्ति होगी।",
    love: "Deeply caring, magnetic, supportive, and emotionally secure partnership.",
    loveHi: "सच्चा और गहरा प्यार, समर्पण और भावनात्मक रूप से सुरक्षित रिश्ता।",
    career: "Intuitive management, creative direction, mentoring teams to great heights.",
    careerHi: "कुशल प्रबंधन, रचनात्मक नेतृत्व और कार्यक्षेत्र में मान-सम्मान।",
    health: "Hormonal and emotional balance, self-care routines, radiant glow.",
    healthHi: "भावनात्मक संतुलन, स्वयं की देखभाल और चेहरे पर तेज।",
    advice: "Lead with empathy and regal self-respect. Your heart holds the answer.",
    adviceHi: "प्रेम और आत्मसम्मान के साथ निर्णय लें। आपका दिल सही राह जानता है।",
    symbolism: "Enthroned Queen surrounded by lush nature or ornate elemental regalia.",
    symbolismHi: "सिंहासन पर विराजमान रानी जो करुणा और अधिकार से युक्त है।"
  },
  "King": {
    rankHi: "राजा (King)",
    astrology: "Air / Fire of the Suit / Supreme Mastery",
    astrologyHi: "सर्वोच्च अधिकार, परिपक्वता व नियंत्रण",
    yesNo: "Strong Yes",
    yesNoHi: "दृढ़ हाँ (Strong Yes)",
    essenceSuffix: "mastery, visionary authority, stability, wisdom, and strategic dominion.",
    essenceSuffixHi: "सर्वोच्च महारत, दूरदर्शी नेतृत्व, स्थायित्व, ज्ञान और रणनीतिक अधिकार।",
    keywords: ["Mastery", "Authority", "Wisdom", "Leadership", "Stability"],
    keywordsHi: ["अधिकार", "महारत", "बुद्धिमत्ता", "नेतृत्व", "स्थायित्व"],
    uprightDesc: "The King represents the pinnacle of outer achievement, strategic mastery, and ethical authority. Command your life with confidence and calm wisdom.",
    uprightDescHi: "किंग संपूर्ण परिपक्वता, रणनीतिक कुशलता और सर्वोच्च अधिकार का प्रतीक है। अपने जीवन का संचालन बुद्धिमत्ता से करें।",
    past: "Wise leadership or structural mastery in the past created this current realm of success.",
    pastHi: "अतीत के आपके दूरदर्शी निर्णयों ने आज इस सफलता का साम्राज्य खड़ा किया है।",
    present: "Take authoritative, fair, and decisive charge of the situation.",
    presentHi: "धैर्य और अधिकार के साथ निर्णय लें; लोग आपके मार्गदर्शन की ओर देख रहे हैं।",
    future: "Reaching the absolute pinnacle of career, financial security, and respected authority.",
    futureHi: "कैरियर के सर्वोच्च शिखर, अपार धन-संपत्ति और मान-सम्मान की प्राप्ति।",
    love: "Devoted, protective, mature, and dependable life partner.",
    loveHi: "जिम्मेदार, सुरक्षात्मक और परिपक्व साथी जो हमेशा साथ निभाएगा।",
    career: "Executive director, business owner, industry authority, major financial gains.",
    careerHi: "उच्चतम पद, व्यापार के मालिक, उद्योग में शीर्ष स्थान और बड़ा आर्थिक लाभ।",
    health: "Disciplined longevity, mental fortitude, robust executive vitality.",
    healthHi: "अनुशासित जीवनशैली और मजबूत मानसिक व शारीरिक स्वास्थ्य।",
    advice: "Command your world with wisdom, fairness, and unwavering vision.",
    adviceHi: "न्यायप्रियता और दूरदर्शिता के साथ अपने जीवन का नेतृत्व करें।",
    symbolism: "King seated on elevated stone throne holding the golden scepter of the suit.",
    symbolismHi: "भव्य सिंहासन पर आसीन राजा जो ज्ञान और शक्ति से शासन करता है।"
  }
};

// Generate full Minor Arcana dynamically so every single card has bespoke, flawless rich data!
Object.keys(MINOR_SUITS_CONFIG).forEach(suitName => {
  const suitConfig = MINOR_SUITS_CONFIG[suitName];
  Object.keys(MINOR_RANKS_DETAILS).forEach(rankName => {
    const rankConfig = MINOR_RANKS_DETAILS[rankName];
    const cardKey = `${rankName.toLowerCase()} of ${suitName.toLowerCase()}`;
    const fullNameEn = `${rankName} of ${suitName}`;
    const fullNameHi = `${rankConfig.rankHi} - ${suitConfig.suitHi}`;

    TAROT_CARDS_DATA[cardKey] = {
      id: cardKey.replace(/\s+/g, '-'),
      name: fullNameEn,
      nameHi: fullNameHi,
      arcana: "Minor",
      suit: suitName as any,
      rank: rankName,
      numeral: rankName === 'Ace' ? 'A' : rankName === 'Page' ? 'P' : rankName === 'Knight' ? 'Kn' : rankName === 'Queen' ? 'Q' : rankName === 'King' ? 'K' : rankName,
      element: suitConfig.element,
      elementHi: suitConfig.elementHi,
      astrology: `${suitName} (${suitConfig.element}) • ${rankConfig.astrology}`,
      astrologyHi: `${suitConfig.suitHi} (${suitConfig.elementHi}) • ${rankConfig.astrologyHi}`,
      yesNo: rankConfig.yesNo,
      yesNoHi: rankConfig.yesNoHi,
      essence: `${fullNameEn} signifies ${suitConfig.theme.toLowerCase().slice(0, -1)} infused with ${rankConfig.essenceSuffix}`,
      essenceHi: `${fullNameHi} ${suitConfig.themeHi} के साथ ${rankConfig.essenceSuffixHi}`,
      keywords: rankConfig.keywords,
      keywordsHi: rankConfig.keywordsHi,
      uprightMeaning: `${fullNameEn}: ${rankConfig.uprightDesc} Channel the ${suitConfig.element} element to fulfill your goals.`,
      uprightMeaningHi: `${fullNameHi}: ${rankConfig.uprightDescHi} ${suitConfig.elementHi} की सकारात्मक ऊर्जा से अपने कार्यों को सिद्ध करें।`,
      pastMeaning: rankConfig.past,
      pastMeaningHi: rankConfig.pastHi,
      presentMeaning: rankConfig.present,
      presentMeaningHi: rankConfig.presentHi,
      futureMeaning: rankConfig.future,
      futureMeaningHi: rankConfig.futureHi,
      love: rankConfig.love,
      loveHi: rankConfig.loveHi,
      career: rankConfig.career,
      careerHi: rankConfig.careerHi,
      health: rankConfig.health,
      healthHi: rankConfig.healthHi,
      advice: rankConfig.advice,
      adviceHi: rankConfig.adviceHi,
      symbolism: `${suitConfig.icon} ${suitName} emblem with ${rankConfig.symbolism}`,
      symbolismHi: `${suitConfig.icon} ${suitConfig.suitHi} का प्रतीक और ${rankConfig.symbolismHi}`,
      icon: suitConfig.icon,
      colorGradient: suitConfig.gradient,
      accentBorder: suitConfig.border
    };
  });
});

/**
 * Robust Tarot card finder that accurately matches full names, minor arcana strings, etc.
 */
export function getTarotCardDetails(cardName: string): TarotCardDetails {
  if (!cardName) return TAROT_CARDS_DATA["the fool"];

  const cleaned = cardName.trim().toLowerCase();

  // 1. Direct match
  if (TAROT_CARDS_DATA[cleaned]) {
    return TAROT_CARDS_DATA[cleaned];
  }

  // 2. Normalized without "the "
  const withoutThe = cleaned.replace(/^the\s+/, '');
  if (TAROT_CARDS_DATA[withoutThe]) {
    return TAROT_CARDS_DATA[withoutThe];
  }
  if (TAROT_CARDS_DATA[`the ${withoutThe}`]) {
    return TAROT_CARDS_DATA[`the ${withoutThe}`];
  }

  // 3. Match minor arcana pattern like "Ace of Cups", "3 of Wands"
  const rankMap: Record<string, string> = {
    '1': 'ace',
    '2': '2',
    '3': '3',
    '4': '4',
    '5': '5',
    '6': '6',
    '7': '7',
    '8': '8',
    '9': '9',
    '10': '10',
    'two': '2',
    'three': '3',
    'four': '4',
    'five': '5',
    'six': '6',
    'seven': '7',
    'eight': '8',
    'nine': '9',
    'ten': '10'
  };

  for (const [key, value] of Object.entries(TAROT_CARDS_DATA)) {
    if (key.toLowerCase() === cleaned) return value;
    if (value.name.toLowerCase() === cleaned) return value;
  }

  // Partial match
  for (const [key, value] of Object.entries(TAROT_CARDS_DATA)) {
    if (cleaned.includes(key) || key.includes(cleaned)) {
      return value;
    }
  }

  // Fallback default
  return TAROT_CARDS_DATA["the fool"];
}
